import {
  BadgeCheck, BriefcaseBusiness, CalendarClock, CalendarDays, ChartNoAxesCombined,
  ClipboardCheck, ClipboardList, ClipboardPenLine, Database, Eye, Flag,
  GraduationCap, Handshake, Headset, Laptop, LayoutGrid, ListChecks, MapPin,
  Megaphone, MessageCircle, Package, Phone, Presentation, Route, Search,
  Send, ShieldCheck, ShoppingBag, Sparkles, Store, Target, TrendingUp,
  Truck, UserCheck, UserRoundSearch, UsersRound, Workflow, Zap,
  type LucideIcon,
} from "lucide-react";
import type { SolutionSlug } from "@/types/solution-detail.types";

export const solutionIcons = {
  "workforce-solutions": UsersRound,
  "sales-force": TrendingUp,
  "promoter-solutions": Megaphone,
  "retail-execution": Store,
  "brand-activation": Flag,
  "business-operations": Headset,
  "gig-workforce": CalendarClock,
} satisfies Record<SolutionSlug, LucideIcon>;

export const solutionStageIcons = {
  "workforce-solutions": [ClipboardList, UserRoundSearch, UserCheck, Send],
  "sales-force": [MapPin, UsersRound, Zap, ChartNoAxesCombined],
  "promoter-solutions": [Megaphone, Presentation, MapPin, MessageCircle],
  "retail-execution": [Route, Store, ClipboardCheck, ChartNoAxesCombined],
  "brand-activation": [UsersRound, ClipboardPenLine, Flag, ListChecks],
  "business-operations": [Workflow, UserRoundSearch, Handshake, Headset],
  "gig-workforce": [ClipboardList, UserCheck, Presentation, BadgeCheck],
} satisfies Record<SolutionSlug, readonly [LucideIcon, LucideIcon, LucideIcon, LucideIcon]>;

const activityIcons: Record<string, LucideIcon> = {
  "Permanent recruitment": BadgeCheck,
  "Contract staffing": ClipboardPenLine,
  "Temporary staffing": CalendarClock,
  "Bulk hiring": UsersRound,
  "Project-based hiring": ListChecks,
  "Blue collar hiring": Package,
  "White collar hiring": BriefcaseBusiness,
  "Gig workforce": Zap,
  "Remote workforce": Laptop,
  "Recruitment process outsourcing": Workflow,
  "Field sales executives": Route,
  "Sales officers": BadgeCheck,
  "Business development executives": Handshake,
  "Territory sales teams": MapPin,
  "Telesales teams": Headset,
  "Telecalling teams": Phone,
  "Lead generation teams": Target,
  "Sales promoters": ShoppingBag,
  "Brand promoters": Flag,
  "Product demonstrators": Presentation,
  "Brand ambassadors": Megaphone,
  "Event promoters": CalendarDays,
  "In-store promoters": Store,
  "Merchandising": LayoutGrid,
  "Store audits": ClipboardCheck,
  "Retail audits": ShieldCheck,
  "Mystery audits": Eye,
  "Product availability checks": Package,
  "Shelf management": LayoutGrid,
  "Visual merchandising": Sparkles,
  "Competitor analysis": Search,
  "Market surveys": ClipboardPenLine,
  "BTL campaigns": Megaphone,
  "Brand activation": Flag,
  "Product sampling": ShoppingBag,
  "Product demonstration": Presentation,
  "Mall activation": Store,
  "College activation": GraduationCap,
  "Roadshows": Truck,
  "Events": CalendarDays,
  "Consumer engagement": MessageCircle,
  "Lead generation": Target,
  "Telecalling": Phone,
  "Telesales": Headset,
  "Customer support": MessageCircle,
  "Data collection": Database,
  "Data verification": ShieldCheck,
  "Back office support": Workflow,
  "Remote recruitment teams": UserRoundSearch,
  "Remote sales teams": Laptop,
  "Promoters": Megaphone,
  "Sales executives": TrendingUp,
  "Field executives": MapPin,
  "Telecallers": Phone,
  "Recruiters": UserRoundSearch,
  "Operations staff": Workflow,
};

export function getActivityIcon(title: string): LucideIcon {
  return activityIcons[title] ?? BriefcaseBusiness;
}
