"use client";

import Link from "next/link";
import { useCallback, useState, type FormEvent } from "react";
import { ArrowUpRight, CheckCheck, MapPin, Plus, Search, UsersRound, X } from "lucide-react";
import { cancelAssignment, createAssignment, endAssignment, getAssignments, getSelectedCandidates, updateAssignment } from "@/services/attendance.service";
import type { Assignment, AssignmentInput, SelectedCandidate } from "@/types/attendance.types";
import { businessDate, useBusinessResource } from "../BusinessDashboardUI";
import { attendanceError, AttendanceError, attendanceHref, AttendanceLoading, AttendancePages, clock, todayIST } from "./AttendanceUI";

export function AssignmentManager({ accountId }: { accountId: string }) {
  const [adding, setAdding] = useState(false); const [query, setQuery] = useState(""); const [search, setSearch] = useState("");
  const [page, setPage] = useState(1); const [version, setVersion] = useState(0);
  const [receipt, setReceipt] = useState<{ id: string; created: boolean } | null>(null);
  const request = useCallback((signal: AbortSignal) => getAssignments(query, page, signal), [query, page]);
  const { data, loading, error } = useBusinessResource(`${accountId}:${query}:${page}:${version}`, request);
  return <section><div className="zb-att-section-heading"><div><h2>Team assignments</h2><p>Confirm a selected person’s site, dates and shift before tracking attendance.</p></div><button type="button" className="zb-biz-button" onClick={() => setAdding(value => !value)} aria-expanded={adding}>{adding ? <X aria-hidden="true" /> : <Plus aria-hidden="true" />}{adding ? "Close setup" : "New assignment"}</button></div>
    {receipt && <div role="status" className="zb-att-success"><CheckCheck aria-hidden="true" /><span>{receipt.created ? "Assignment created." : "This candidate already has an assignment; its details were preserved."} <Link href={attendanceHref(true, receipt.id)}>Open assignment<ArrowUpRight aria-hidden="true" /></Link></span></div>}
    {adding && <NewAssignment key={`${accountId}:${version}`} accountId={accountId} onSaved={result => { setReceipt(result); setAdding(false); setVersion(v => v + 1); }} />}
    <form className="zb-att-filters zb-att-filters--search" onSubmit={e => { e.preventDefault(); setQuery(search.trim()); setPage(1); }}><label><span>Search assignments</span><input value={search} onChange={e => setSearch(e.target.value)} maxLength={100} placeholder="Person, site or company" /></label><button className="zb-biz-button zb-biz-button--secondary" type="submit"><Search aria-hidden="true" />Search</button></form>
    {loading ? <AttendanceLoading /> : error ? <AttendanceError admin error={error} retry={() => setVersion(v => v + 1)} /> : data && <>{!data.total ? <div className="zb-att-empty"><UsersRound aria-hidden="true" /><h3>{query ? "No matching assignments" : "Build the roster from selected people"}</h3><p>{query ? "Try another name, company or site." : "Use New assignment after the business selects a candidate in the candidate pipeline."}</p><Link className="zb-biz-text-link" href="/admin/candidate-management">Open candidate pipeline<ArrowUpRight aria-hidden="true" /></Link></div> : <div className="zb-att-assignment-grid">{data.items.map(item => <article key={item.id} className="zb-att-assignment-card"><span className="zb-att-assignment-state">{item.cancelledAt ? "Cancelled" : item.startDate > data.today ? "Upcoming" : item.endDate < data.today ? "Ended" : "Active"}</span><h3>{item.name}</h3><p>{item.role} · {item.requirement.companyName}</p><p><MapPin aria-hidden="true" />{item.location}</p><dl><div><dt>Dates</dt><dd>{businessDate(item.startDate)} – {businessDate(item.endDate)}</dd></div><div><dt>Shift (IST)</dt><dd>{clock(item.shiftStart)}–{clock(item.shiftEnd)}{item.shiftEnd < item.shiftStart && " (+1 day)"}</dd></div></dl><Link className="zb-att-record-link" href={attendanceHref(true, item.id)}>Calendar & settings<ArrowUpRight aria-hidden="true" /></Link></article>)}</div>}<AttendancePages page={data.page} totalPages={data.totalPages} onChange={setPage} /></>}
  </section>;
}

function NewAssignment({ accountId, onSaved }: { accountId: string; onSaved: (value: { id: string; created: boolean }) => void }) {
  const [candidate, setCandidate] = useState<SelectedCandidate | null>(null);
  return <div className="zb-att-setup"><h3><span>01</span> Choose a selected candidate</h3>{candidate ? <div className="zb-att-context"><UsersRound aria-hidden="true" /><span><strong>{candidate.name}</strong>{candidate.jobTitle} · {candidate.requirement.companyName}</span><button type="button" onClick={() => setCandidate(null)}>Change</button></div> : <SelectedCandidatePicker accountId={accountId} onSelect={setCandidate} />}
    {candidate && <><h3><span>02</span> Confirm the assignment</h3><AssignmentForm key={candidate.id} defaultLocation={candidate.requirement.jobLocation} onSave={async values => { const result = await createAssignment({ ...values, candidateId: candidate.id }); onSaved(result.data); }} /></>}
  </div>;
}
function SelectedCandidatePicker({ accountId, onSelect }: { accountId: string; onSelect: (item: SelectedCandidate) => void }) {
  const [search, setSearch] = useState(""); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [version, setVersion] = useState(0);
  const request = useCallback((signal: AbortSignal) => getSelectedCandidates(query, page, signal), [query, page]);
  const { data, loading, error } = useBusinessResource(`${accountId}:${query}:${page}:${version}`, request);
  return <div><form className="zb-att-filters zb-att-filters--search" onSubmit={e => { e.preventDefault(); setQuery(search.trim()); setPage(1); }}><label><span>Search selected candidates</span><input value={search} onChange={e => setSearch(e.target.value)} maxLength={100} placeholder="Name, company or role" /></label><button type="submit" className="zb-biz-button zb-biz-button--secondary">Search</button></form>{loading ? <AttendanceLoading /> : error ? <AttendanceError admin error={error} retry={() => setVersion(v => v + 1)} /> : data && <>{!data.total ? <p>No unassigned selected candidates match this view. The business must select a shared profile first.</p> : <ul className="zb-att-picker">{data.items.map(item => <li key={item.id}><button type="button" onClick={() => onSelect(item)}><span><strong>{item.name}</strong><small>{item.jobTitle} · {item.requirement.companyName} · {item.requirement.jobLocation}</small></span><Plus aria-hidden="true" /></button></li>)}</ul>}<AttendancePages page={data.page} totalPages={data.totalPages} onChange={setPage} /></>}<p className="zb-att-muted">Only selected people on open requirements owned by active business accounts can be assigned.</p></div>;
}
const weekdays = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
export function AssignmentForm({ assignment, defaultLocation = "", onSave }: { assignment?: Assignment; defaultLocation?: string; onSave: (values: AssignmentInput, note: string) => Promise<void> }) {
  const [values, setValues] = useState<AssignmentInput>(() => ({ location: assignment?.location ?? defaultLocation, supervisor: assignment?.supervisor ?? "",
    startDate: assignment?.startDate ?? todayIST(), endDate: assignment?.endDate ?? todayIST(), shiftStart: assignment ? clock(assignment.shiftStart) : "09:00", shiftEnd: assignment ? clock(assignment.shiftEnd) : "18:00",
    graceMinutes: assignment?.graceMinutes ?? 10, workingDays: assignment?.workingDays ?? [1, 2, 3, 4, 5, 6] }));
  const [note, setNote] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  function field<K extends keyof AssignmentInput>(key: K, value: AssignmentInput[K]) { setValues(current => ({ ...current, [key]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); if (busy) return; if (!values.workingDays.length) { setError("Select at least one working day."); return; } setBusy(true); setError(""); try { await onSave(values, note); } catch (error) { setError(attendanceError(error)); } finally { setBusy(false); } }
  return <form className="zb-att-form" onSubmit={submit}><fieldset disabled={busy}><div className="zb-att-form-grid"><label><span>Site / work location *</span><input required minLength={2} maxLength={160} value={values.location} onChange={e => field("location", e.target.value)} /></label><label><span>Supervisor name *</span><input required minLength={2} maxLength={120} value={values.supervisor} onChange={e => field("supervisor", e.target.value)} /></label><label><span>Start date *</span><input type="date" required min="2000-01-01" max="2099-12-31" value={values.startDate} onChange={e => field("startDate", e.target.value)} /></label><label><span>Last working date *</span><input type="date" required min={values.startDate || "2000-01-01"} max="2099-12-31" value={values.endDate} onChange={e => field("endDate", e.target.value)} /></label><label><span>Shift start (IST) *</span><input type="time" required value={values.shiftStart} onChange={e => field("shiftStart", e.target.value)} /></label><label><span>Shift end (IST) *</span><input type="time" required value={values.shiftEnd} onChange={e => field("shiftEnd", e.target.value)} /></label><label><span>Late-arrival grace (minutes) *</span><input type="number" required min={0} max={60} value={values.graceMinutes} onChange={e => field("graceMinutes", Number(e.target.value))} /></label></div>
      <fieldset className="zb-att-weekdays"><legend>Working days *</legend>{weekdays.map((day, i) => <label key={day}><input type="checkbox" checked={values.workingDays.includes(i + 1)} onChange={e => field("workingDays", e.target.checked ? [...values.workingDays, i + 1].sort() : values.workingDays.filter(value => value !== i + 1))} /><span>{day}</span></label>)}</fieldset><p className="zb-att-muted">An earlier end time means the shift finishes the next day. Use a shift of 1–16 hours and an assignment of up to 367 calendar dates. Schedule changes lock after the first attendance entry or correction request.</p>
      {assignment && <label><span>Reason for changing settings *</span><textarea required minLength={3} maxLength={1500} rows={2} value={note} onChange={e => setNote(e.target.value)} /></label>}{error && <p role="alert" className="zb-biz-error">{error}</p>}<button className="zb-biz-button" type="submit">{busy ? "Saving…" : assignment ? assignment.cancelledAt ? "Save and reactivate assignment" : "Save assignment settings" : "Create assignment"}</button>
    </fieldset></form>;
}
export function AssignmentSettings({ assignment, settingsLocked, onChanged }: { assignment: Assignment; settingsLocked: boolean; onChanged: () => void }) {
  const [action, setAction] = useState("end"); const [endDate, setEndDate] = useState(assignment.endDate); const [note, setNote] = useState("");
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (busy) return; setBusy(true); setError(""); try {
    if (action === "cancel") await cancelAssignment(assignment.id, assignment.revision, note); else await endAssignment(assignment.id, assignment.revision, endDate, note);
    setNotice(action === "cancel" ? "Assignment cancelled." : "Assignment end date saved."); onChanged();
  } catch (error) { setError(attendanceError(error)); } finally { setBusy(false); } }
  return <details className="zb-att-settings"><summary>Assignment settings & end date</summary>{notice && <p role="status" className="zb-att-success">{notice}</p>}{!settingsLocked ? <AssignmentForm key={assignment.revision} assignment={assignment} onSave={async (values, note) => { await updateAssignment(assignment.id, { ...values, revision: assignment.revision, note }); setNotice("Assignment settings saved."); onChanged(); }} /> : <p className="zb-att-notice">This assignment has attendance or correction history. Its schedule is preserved. You can end future roster dates below.</p>}
    {!assignment.cancelledAt && <form className="zb-att-form" onSubmit={submit}><fieldset disabled={busy}><h3>End or cancel assignment</h3><label><span>Action</span><select value={action} onChange={e => setAction(e.target.value)}><option value="end">End on a chosen date</option>{!settingsLocked && <option value="cancel">Cancel assignment without history</option>}</select></label>{action === "end" && <label><span>Last included date *</span><input required type="date" min={assignment.startDate} max={assignment.endDate} value={endDate} onChange={e => setEndDate(e.target.value)} /></label>}<label><span>Reason *</span><textarea required minLength={3} maxLength={1500} rows={2} value={note} onChange={e => setNote(e.target.value)} /></label><p className="zb-att-muted">Recorded dates and correction history will be preserved. Ending an assignment removes later dates from the roster.</p><label className="zb-att-confirm"><input type="checkbox" required />I have checked this change with the operations team.</label>{error && <p role="alert" className="zb-biz-error">{error}</p>}<button className="zb-biz-button zb-biz-button--secondary" type="submit">{busy ? "Saving…" : action === "end" ? "Save last working date" : "Cancel assignment"}</button></fieldset></form>}
  </details>;
}
