"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import {
  ArrowLeft, ArrowRight, BadgeCheck, Banknote, BriefcaseBusiness, Building2, CalendarDays, CheckCircle2, ClipboardCheck,
  Download, FileCheck2, FileText, GraduationCap, IdCard, Inbox, LoaderCircle, Mail, MapPin, Phone, RefreshCw, Search,
  Send, ShieldCheck, Signature, UserRound,
} from "lucide-react";
import { apiFetch, ApiError, type ApiSuccessEnvelope } from "@/lib/api";
import { getCurrentUser } from "@/services/auth.service";
import "@/styles/hr-admin.css";

interface DocumentRecord { id: string; kind: string; fileName: string; mimeType: string; size: number; createdAt: string }
interface OfferRecord {
  id: string; status: "DRAFT" | "APPROVED" | "ISSUING" | "ISSUED"; designation: string; department: string; projectAssignment: string; workLocation: string;
  joiningDate: string; employmentType: string; monthlyGrossSalary: number; annualCtc: number; probationMonths: number; noticePeriodDays: number;
  additionalTerms?: string | null; authorizedSignatoryName?: string | null; authorizedSignatoryTitle?: string | null; signatureFileName?: string | null;
  approvedAt?: string | null; issuedAt?: string | null; sentAt?: string | null; resendMessageId?: string | null; revision: number; updatedAt: string;
}
interface JoiningRecord {
  id: string; employeeNumber: string; projectCode: string; projectAssignment: string; fullName: string; fatherGuardianName?: string; personalEmail: string; phone: string; alternatePhone?: string | null;
  dateOfBirth?: string; gender?: string; maritalStatus?: string | null; bloodGroup?: string | null; shirtSize?: string | null;
  currentAddressLine1?: string; currentAddressLine2?: string | null; currentCity: string; currentState: string; currentPostalCode?: string;
  permanentSameAsCurrent?: boolean; permanentAddressLine1?: string; permanentAddressLine2?: string | null; permanentCity?: string; permanentState?: string; permanentPostalCode?: string;
  emergencyContactName?: string; emergencyRelationship?: string; emergencyPhone?: string;
  aadhaar?: string; pan?: string; bankAccount?: string; aadhaarNumber?: string; panNumber?: string; bankAccountHolder?: string; bankName?: string; bankAccountNumber?: string;
  ifscCode?: string; bankBranch?: string; upiId?: string | null; uanNumber?: string; highestQualification?: string; institution?: string; boardUniversity?: string | null;
  graduationYear?: number | null; grade?: string | null; previousEmployment?: Array<Record<string, unknown>>; status: string; reviewNotes?: string | null; reviewedAt?: string | null;
  submittedAt: string; approvedAt?: string | null; createdAt: string; updatedAt: string; revision: number; documents: DocumentRecord[]; offer?: OfferRecord | null;
  history?: Array<{ id: string; action: string; createdAt: string; metadata?: Record<string, unknown> | null }>;
}
interface ListData { items: JoiningRecord[]; total: number; page: number; totalPages: number; counts: Record<string, number> }

type OfferForm = { designation: string; department: string; projectAssignment: string; workLocation: string; joiningDate: string; employmentType: string; monthlyGrossSalary: number; annualCtc: number; probationMonths: number; noticePeriodDays: number; additionalTerms: string; authorizedSignatoryName: string; authorizedSignatoryTitle: string };
const blankOffer = (joining: JoiningRecord): OfferForm => ({ designation: "", department: "", projectAssignment: joining.projectAssignment, workLocation: `${joining.currentCity}, ${joining.currentState}`, joiningDate: "", employmentType: "FULL_TIME", monthlyGrossSalary: 0, annualCtc: 0, probationMonths: 3, noticePeriodDays: 30, additionalTerms: "", authorizedSignatoryName: "", authorizedSignatoryTitle: "Authorized Signatory" });
const statusLabel = (value: string) => value.toLowerCase().replaceAll("_", " ").replace(/^./, letter => letter.toUpperCase());
const date = (value?: string | null) => value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(value)) : "—";
const money = (value?: number | null) => value == null ? "—" : new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);
function Badge({ value }: { value: string }) { return <span className="zhr-admin-badge" data-status={value}>{statusLabel(value)}</span>; }
function Panel({ title, icon: Icon, children }: { title: string; icon: typeof FileText; children: ReactNode }) { return <section className="zhr-admin-panel"><h2><Icon />{title}</h2>{children}</section>; }

function EmploymentHistory({ items }: { items?: Array<Record<string, unknown>> }) {
  if (!items?.length) return <p className="zhr-admin-muted">No previous employment declared.</p>;
  return <div className="zhr-admin-employment">{items.map((item, index) => {
    const company = typeof item.company === "string" ? item.company : "Previous employer";
    const designation = typeof item.designation === "string" ? item.designation : "Designation not provided";
    const start = typeof item.startDate === "string" ? date(item.startDate) : "—";
    const current = item.current === true;
    const end = current ? "Present" : typeof item.endDate === "string" && item.endDate ? date(item.endDate) : "—";
    const salary = typeof item.lastMonthlySalary === "number" ? money(item.lastMonthlySalary) : "—";
    const reason = typeof item.reasonForLeaving === "string" && item.reasonForLeaving.trim() ? item.reasonForLeaving : "Not provided";
    return <article key={`${company}-${index}`}><div><BriefcaseBusiness /><span><strong>{company}</strong><small>{designation}</small></span></div><dl><div><dt>Period</dt><dd>{start} – {end}</dd></div><div><dt>Last monthly salary</dt><dd>{salary}</dd></div><div><dt>Reason for leaving</dt><dd>{reason}</dd></div></dl></article>;
  })}</div>;
}

async function download(path: string, filename: string) {
  const response = await fetch(`/api/backend${path}`, { credentials: "include", cache: "no-store" });
  if (!response.ok) throw new ApiError(`Download failed (${response.status}).`, response.status);
  const url = URL.createObjectURL(await response.blob());
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 10_000);
}

async function signatureAsJpeg(file: File) {
  if (file.size > 3 * 1024 * 1024) throw new Error("Choose a signature image smaller than 3 MB.");
  if (!["image/jpeg", "image/png"].includes(file.type)) throw new Error("Choose a JPG or PNG signature image.");
  const source = URL.createObjectURL(file);
  try {
    const image = await new Promise<HTMLImageElement>((resolve, reject) => {
      const element = document.createElement("img");
      element.onload = () => resolve(element);
      element.onerror = () => reject(new Error("Your browser could not read the signature image."));
      element.src = source;
    });
    const scale = Math.min(1, 1200 / Math.max(image.naturalWidth, image.naturalHeight));
    const canvas = document.createElement("canvas");
    canvas.width = Math.max(1, Math.round(image.naturalWidth * scale));
    canvas.height = Math.max(1, Math.round(image.naturalHeight * scale));
    const context = canvas.getContext("2d");
    if (!context) throw new Error("Your browser could not prepare the signature image.");
    context.fillStyle = "#ffffff";
    context.fillRect(0, 0, canvas.width, canvas.height);
    context.drawImage(image, 0, 0, canvas.width, canvas.height);
    const blob = await new Promise<Blob | null>(resolve => canvas.toBlob(resolve, "image/jpeg", .92));
    if (!blob) throw new Error("Your browser could not prepare the signature image.");
    return new File([blob], file.name.replace(/\.[^.]+$/, "") + ".jpg", { type: "image/jpeg" });
  } finally {
    URL.revokeObjectURL(source);
  }
}

export function AdminEmployeeJoiningList() {
  const router = useRouter(); const [data, setData] = useState<ListData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [projectCode, setProjectCode] = useState(""); const [version, setVersion] = useState(0);
  useEffect(() => { const controller = new AbortController(); let active = true; async function load() { setLoading(true); setError(""); try { const current = await getCurrentUser(); if (!active) return; if (current.data.user.role !== "ADMIN") { router.replace("/login"); return; } if (!current.data.user.adminMfaEnabled) { router.replace("/admin/security"); return; } const params = new URLSearchParams({ page: String(page), query }); if (status) params.set("status", status); if (projectCode) params.set("projectCode", projectCode); const response = await apiFetch<ApiSuccessEnvelope<ListData>>(`/admin/employee-joining?${params}`, { signal: controller.signal }); if (active) setData(response.data); } catch (caught) { if (!active || controller.signal.aborted) return; if (caught instanceof ApiError && [401,403].includes(caught.status)) router.replace("/login"); else setError(caught instanceof Error ? caught.message : "Unable to load employee joining records."); } finally { if (active) setLoading(false); } } queueMicrotask(() => void load()); return () => { active = false; controller.abort(); }; }, [page, query, status, projectCode, version, router]);
  const stats = useMemo(() => data ? [{ label: "Received", value: Object.values(data.counts).reduce((a,b)=>a+b,0), icon: Inbox }, { label: "Under review", value: data.counts.UNDER_REVIEW ?? 0, icon: ClipboardCheck }, { label: "Approved", value: data.counts.APPROVED ?? 0, icon: BadgeCheck }, { label: "Rejected", value: data.counts.REJECTED ?? 0, icon: FileText }] : [], [data]);
  async function exportRecords() { setError(""); try { await download("/admin/employee-joining/export.csv", "zobhunger-employee-records.csv"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to export employee records."); } }
  return <div className="zhr-admin"><nav className="zhr-admin-nav"><Link href="/admin"><ArrowLeft />Admin dashboard</Link></nav><header className="zhr-admin-hero"><div><p className="zhr-admin-kicker">HR OPERATIONS · EMPLOYEE JOINING</p><h1>Joining records, documents and offer letters.</h1><p>Review every employee submission, maintain the HR record, export it for Excel/Google Sheets and move approved employees into the offer-letter workflow.</p></div><div className="zhr-admin-hero-actions"><button onClick={() => void exportRecords()}><Download />Export for Excel / Sheets</button><button className="secondary" onClick={() => setVersion(v => v + 1)}><RefreshCw />Refresh</button></div></header>
    {data && <div className="zhr-admin-stats">{stats.map(({label,value,icon:Icon}) => <article key={label}><Icon /><span>{label}</span><strong>{value}</strong></article>)}</div>}
    <form className="zhr-admin-filters" onSubmit={event => { event.preventDefault(); setPage(1); setQuery(search.trim()); }}><label><span>Search</span><div><Search /><input type="search" value={search} onChange={e => setSearch(e.target.value)} maxLength={160} placeholder="Name, employee ID, email, project" /></div></label><label><span>Status</span><select value={status} onChange={e => { setPage(1); setStatus(e.target.value); }}><option value="">All statuses</option>{["SUBMITTED","UNDER_REVIEW","APPROVED","REJECTED"].map(value => <option key={value} value={value}>{statusLabel(value)}</option>)}</select></label><label><span>Project code</span><input value={projectCode} onChange={e => { setPage(1); setProjectCode(e.target.value.toUpperCase().replace(/[^A-Z0-9-]/g,"")); }} maxLength={16} placeholder="e.g. PL" /></label><button type="submit">Search</button></form>
    {loading && <div className="zhr-admin-state"><LoaderCircle className="zhr-spin" />Loading employee records…</div>}{error && <div className="zhr-admin-error">{error}</div>}
    {data && !loading && <>{data.items.length ? <div className="zhr-admin-cards">{data.items.map(item => <article key={item.id}><div className="zhr-admin-card-top"><span className="zhr-admin-avatar"><UserRound /></span><Badge value={item.status} /></div><p className="zhr-admin-code">{item.employeeNumber}</p><h2>{item.fullName}</h2><p>{item.projectAssignment}</p><div className="zhr-admin-card-meta"><span><MapPin />{item.currentCity}, {item.currentState}</span><span><FileCheck2 />{item.documents.length} documents</span><span><BriefcaseBusiness />{item.offer ? `Offer: ${statusLabel(item.offer.status)}` : "Offer not started"}</span></div><small>Submitted {date(item.submittedAt)}</small><Link href={`/admin/employee-joining/${item.id}`}>Open HR record<ArrowRight /></Link></article>)}</div> : <div className="zhr-admin-state"><Inbox />No employee joining records match these filters.</div>}<div className="zhr-admin-pagination"><button disabled={page <= 1} onClick={() => setPage(p => p-1)}>Previous</button><span>Page {data.page} of {data.totalPages}</span><button disabled={page >= data.totalPages} onClick={() => setPage(p => p+1)}>Next</button></div></>}
  </div>;
}

export function AdminEmployeeJoiningDetail({ id }: { id: string }) {
  const router = useRouter(); const [record, setRecord] = useState<JoiningRecord | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [reviewStatus, setReviewStatus] = useState("UNDER_REVIEW"); const [notes, setNotes] = useState(""); const [offer, setOffer] = useState<OfferForm | null>(null); const [version, setVersion] = useState(0);
  const refresh = useCallback(() => setVersion(v => v+1), []);
  useEffect(() => { const controller = new AbortController(); let active = true; async function load() { setLoading(true); setError(""); try { const current = await getCurrentUser(); if (!active) return; if (current.data.user.role !== "ADMIN") { router.replace("/login"); return; } if (!current.data.user.adminMfaEnabled) { router.replace("/admin/security"); return; } const response = await apiFetch<ApiSuccessEnvelope<JoiningRecord>>(`/admin/employee-joining/${encodeURIComponent(id)}`, { signal: controller.signal }); if (!active) return; setRecord(response.data); setNotes(response.data.reviewNotes ?? ""); setReviewStatus(response.data.status === "SUBMITTED" ? "UNDER_REVIEW" : response.data.status); const currentOffer = response.data.offer; setOffer(currentOffer ? { designation: currentOffer.designation, department: currentOffer.department, projectAssignment: currentOffer.projectAssignment, workLocation: currentOffer.workLocation, joiningDate: currentOffer.joiningDate.slice(0,10), employmentType: currentOffer.employmentType, monthlyGrossSalary: currentOffer.monthlyGrossSalary, annualCtc: currentOffer.annualCtc, probationMonths: currentOffer.probationMonths, noticePeriodDays: currentOffer.noticePeriodDays, additionalTerms: currentOffer.additionalTerms ?? "", authorizedSignatoryName: currentOffer.authorizedSignatoryName ?? "", authorizedSignatoryTitle: currentOffer.authorizedSignatoryTitle ?? "" } : blankOffer(response.data)); } catch (caught) { if (!active || controller.signal.aborted) return; if (caught instanceof ApiError && [401,403].includes(caught.status)) router.replace("/login"); else setError(caught instanceof Error ? caught.message : "Unable to load this employee record."); } finally { if (active) setLoading(false); } } queueMicrotask(() => void load()); return () => { active=false; controller.abort(); }; }, [id, router, version]);
  function offerSet<K extends keyof OfferForm>(key: K, value: OfferForm[K]) { setOffer(current => current ? { ...current, [key]: value } : current); }
  async function action(work: () => Promise<unknown>, success: string) { if (busy) return; setBusy(true); setError(""); setMessage(""); try { await work(); setMessage(success); refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "The HR action could not be completed."); } finally { setBusy(false); } }
  async function review() { if (!record) return; await action(() => apiFetch(`/admin/employee-joining/${id}/review`, { method:"POST", body:JSON.stringify({ status: reviewStatus, notes, expectedRevision: record.revision }) }), "HR review saved."); }
  async function saveOffer(event: FormEvent) { event.preventDefault(); if (!record || !offer) return; await action(() => apiFetch(`/admin/employee-joining/${id}/offer`, { method:"PUT", body:JSON.stringify({ ...offer, expectedRevision: record.offer?.revision ?? 0 }) }), "Offer-letter draft saved."); }
  async function uploadSignature(file?: File) { if (!record || !file) return; await action(async () => { const jpeg = await signatureAsJpeg(file); await apiFetch(`/admin/employee-joining/${id}/offer/signature`, { method:"PUT", headers:{ "Content-Type":"image/jpeg", "X-File-Name":encodeURIComponent(jpeg.name) }, body: await jpeg.arrayBuffer() }); }, "Authorized signature attached."); }
  async function safeDownload(path: string, filename: string) { setError(""); try { await download(path, filename); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to download this HR file."); } }
  if (loading) return <div className="zhr-admin-state"><LoaderCircle className="zhr-spin" />Loading employee record…</div>;
  if (!record) return <div className="zhr-admin-error">{error || "Employee record not found."}</div>;
  const approved = record.status === "APPROVED";
  return <div className="zhr-admin"><nav className="zhr-admin-nav"><Link href="/admin/employee-joining"><ArrowLeft />All joining records</Link></nav><header className="zhr-admin-detail-head"><span className="zhr-admin-avatar"><IdCard /></span><div><p className="zhr-admin-kicker">{record.employeeNumber}</p><h1>{record.fullName}</h1><p>{record.projectAssignment} · {record.projectCode}</p></div><Badge value={record.status} /></header><div className="zhr-admin-contact"><a href={`mailto:${record.personalEmail}`}><Mail />{record.personalEmail}</a><a href={`tel:${record.phone.replace(/[^+\d]/g,"")}`}><Phone />{record.phone}</a><span><MapPin />{record.currentCity}, {record.currentState}</span><span><CalendarDays />Submitted {date(record.submittedAt)}</span></div>{message && <div className="zhr-admin-success"><CheckCircle2 />{message}</div>}{error && <div className="zhr-admin-error">{error}</div>}
    <div className="zhr-admin-detail-grid"><div className="zhr-admin-detail-main">
      <Panel title="Personal & assignment" icon={UserRound}><dl className="zhr-admin-facts"><div><dt>Employee ID</dt><dd>{record.employeeNumber}</dd></div><div><dt>Project code</dt><dd>{record.projectCode}</dd></div><div><dt>Project</dt><dd>{record.projectAssignment}</dd></div><div><dt>Father / guardian</dt><dd>{record.fatherGuardianName}</dd></div><div><dt>Date of birth</dt><dd>{date(record.dateOfBirth)}</dd></div><div><dt>Gender</dt><dd>{record.gender ? statusLabel(record.gender) : "—"}</dd></div><div><dt>Blood group</dt><dd>{record.bloodGroup || "—"}</dd></div><div><dt>Shirt size</dt><dd>{record.shirtSize || "—"}</dd></div></dl></Panel>
      <Panel title="Address & emergency contact" icon={Building2}><div className="zhr-admin-addresses"><div><b>Current address</b><p>{[record.currentAddressLine1,record.currentAddressLine2,record.currentCity,record.currentState,record.currentPostalCode].filter(Boolean).join(", ")}</p></div><div><b>Permanent address</b><p>{[record.permanentAddressLine1,record.permanentAddressLine2,record.permanentCity,record.permanentState,record.permanentPostalCode].filter(Boolean).join(", ")}</p></div></div><dl className="zhr-admin-facts"><div><dt>Emergency contact</dt><dd>{record.emergencyContactName}</dd></div><div><dt>Relationship</dt><dd>{record.emergencyRelationship}</dd></div><div><dt>Phone</dt><dd>{record.emergencyPhone}</dd></div></dl></Panel>
      <Panel title="Statutory & bank record" icon={Banknote}><div className="zhr-admin-sensitive"><ShieldCheck /><span>Sensitive identifiers are decrypted only inside this authenticated HR record. Avoid copying them into unsecured chats or notes.</span></div><dl className="zhr-admin-facts"><div><dt>Aadhaar</dt><dd>{record.aadhaarNumber}</dd></div><div><dt>PAN</dt><dd>{record.panNumber}</dd></div><div><dt>Account holder</dt><dd>{record.bankAccountHolder}</dd></div><div><dt>Bank</dt><dd>{record.bankName}</dd></div><div><dt>Account number</dt><dd>{record.bankAccountNumber}</dd></div><div><dt>IFSC</dt><dd>{record.ifscCode}</dd></div><div><dt>Branch</dt><dd>{record.bankBranch}</dd></div><div><dt>UPI</dt><dd>{record.upiId || "—"}</dd></div><div><dt>UAN / PF</dt><dd>{record.uanNumber || "—"}</dd></div></dl></Panel>
      <Panel title="Education & employment" icon={GraduationCap}><dl className="zhr-admin-facts"><div><dt>Qualification</dt><dd>{record.highestQualification}</dd></div><div><dt>Institution</dt><dd>{record.institution}</dd></div><div><dt>Board / university</dt><dd>{record.boardUniversity || "—"}</dd></div><div><dt>Completion year</dt><dd>{record.graduationYear || "—"}</dd></div><div><dt>Grade</dt><dd>{record.grade || "—"}</dd></div></dl><EmploymentHistory items={record.previousEmployment} /></Panel>
      <Panel title="Employee documents" icon={FileCheck2}><div className="zhr-admin-docs">{record.documents.map(document => <button key={document.id} onClick={() => void safeDownload(`/admin/employee-joining/${id}/documents/${document.id}`, document.fileName)}><FileText /><span><strong>{statusLabel(document.kind)}</strong><small>{document.fileName} · {(document.size/1024/1024).toFixed(2)} MB</small></span><Download /></button>)}</div></Panel>
    </div><aside className="zhr-admin-side">
      <Panel title="HR review" icon={ClipboardCheck}><label className="zhr-admin-field">Status<select value={reviewStatus} disabled={busy || record.status === "APPROVED"} onChange={e => setReviewStatus(e.target.value)}><option value="UNDER_REVIEW">Under review</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option></select></label><label className="zhr-admin-field">Internal notes<textarea rows={5} maxLength={4000} value={notes} onChange={e => setNotes(e.target.value)} /></label><button className="zhr-admin-primary" disabled={busy || record.status === "APPROVED"} onClick={() => void review()}>{busy ? <LoaderCircle className="zhr-spin" /> : <BadgeCheck />}Save HR decision</button>{record.status === "APPROVED" && <p className="zhr-admin-muted">Approved {date(record.approvedAt)}. Offer-letter controls are unlocked.</p>}</Panel>
      {approved && offer && <Panel title="Offer letter" icon={Signature}><form className="zhr-offer-form" onSubmit={saveOffer}><label className="zhr-admin-field">Designation<input required value={offer.designation} onChange={e => offerSet("designation", e.target.value)} /></label><label className="zhr-admin-field">Department<input required value={offer.department} onChange={e => offerSet("department", e.target.value)} /></label><label className="zhr-admin-field">Project / assignment<input required value={offer.projectAssignment} onChange={e => offerSet("projectAssignment", e.target.value)} /></label><label className="zhr-admin-field">Work location<input required value={offer.workLocation} onChange={e => offerSet("workLocation", e.target.value)} /></label><div className="zhr-offer-two"><label className="zhr-admin-field">Joining date<input type="date" required value={offer.joiningDate} onChange={e => offerSet("joiningDate", e.target.value)} /></label><label className="zhr-admin-field">Employment type<select value={offer.employmentType} onChange={e => offerSet("employmentType", e.target.value)}>{["FULL_TIME","PART_TIME","CONTRACT","FIXED_TERM","INTERNSHIP"].map(v=><option key={v} value={v}>{statusLabel(v)}</option>)}</select></label></div><div className="zhr-offer-two"><label className="zhr-admin-field">Monthly gross (INR)<input type="number" min={0} required value={offer.monthlyGrossSalary} onChange={e => offerSet("monthlyGrossSalary", Number(e.target.value))} /></label><label className="zhr-admin-field">Annual CTC (INR)<input type="number" min={0} required value={offer.annualCtc} onChange={e => offerSet("annualCtc", Number(e.target.value))} /></label></div><div className="zhr-offer-two"><label className="zhr-admin-field">Probation months<input type="number" min={0} max={24} value={offer.probationMonths} onChange={e => offerSet("probationMonths", Number(e.target.value))} /></label><label className="zhr-admin-field">Notice days<input type="number" min={0} max={365} value={offer.noticePeriodDays} onChange={e => offerSet("noticePeriodDays", Number(e.target.value))} /></label></div><label className="zhr-admin-field">Authorized signatory<input required value={offer.authorizedSignatoryName} onChange={e => offerSet("authorizedSignatoryName", e.target.value)} /></label><label className="zhr-admin-field">Signatory title<input required value={offer.authorizedSignatoryTitle} onChange={e => offerSet("authorizedSignatoryTitle", e.target.value)} /></label><label className="zhr-admin-field">Additional terms<textarea rows={4} maxLength={5000} value={offer.additionalTerms} onChange={e => offerSet("additionalTerms", e.target.value)} /></label><button className="zhr-admin-primary" type="submit" disabled={busy || record.offer?.status === "ISSUED"}><FileCheck2 />{record.offer ? "Update offer draft" : "Generate offer draft"}</button></form>
        {record.offer && <div className="zhr-offer-actions"><div className="zhr-offer-status"><Badge value={record.offer.status} /><span>{record.offer.signatureFileName ? "Signature attached" : "Signature pending"}</span></div><button className="zhr-admin-secondary" onClick={() => void safeDownload(`/admin/employee-joining/${id}/offer-letter.pdf`, `${record.employeeNumber}-offer-letter.pdf`)}><Download />Download PDF</button>{record.offer.status === "DRAFT" && <button className="zhr-admin-primary" disabled={busy} onClick={() => void action(() => apiFetch(`/admin/employee-joining/${id}/offer/approve`, { method:"POST", body:JSON.stringify({ expectedRevision: record.offer!.revision }) }), "Offer letter approved.")}><BadgeCheck />Approve offer</button>}{record.offer.status === "APPROVED" && <label className="zhr-signature-upload"><input type="file" accept=".jpg,.jpeg,.png,image/jpeg,image/png" disabled={busy} onChange={e => void uploadSignature(e.target.files?.[0])} /><Signature /><span>{record.offer.signatureFileName ? "Replace authorized signature" : "Add authorized signature"}</span></label>}{record.offer.status === "APPROVED" && <button className="zhr-admin-issue" disabled={busy || !record.offer.signatureFileName} onClick={() => { if (window.confirm(`Issue ${record.employeeNumber}'s final offer letter and email it to ${record.personalEmail}?`)) void action(() => apiFetch(`/admin/employee-joining/${id}/offer/issue`, { method:"POST", body:JSON.stringify({ expectedRevision: record.offer!.revision }) }), "Final offer letter issued and emailed to the employee."); }}><Send />Issue & email final offer</button>}{record.offer.status === "ISSUED" && <p className="zhr-admin-success"><CheckCircle2 />Issued {date(record.offer.issuedAt)} and sent to {record.personalEmail}.</p>}</div>}
      </Panel>}
    </aside></div>
  </div>;
}
