"use client";
import Link from "next/link";
import { useCallback, useRef, useState, type FormEvent } from "react";
import { Archive, ArrowLeft, ArrowUpRight, BriefcaseBusiness, CheckCheck, FileCheck2, FilePenLine, MapPin, Plus, RotateCcw, Send, UsersRound } from "lucide-react";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { apiFetch } from "@/lib/api";
import { createLinkedJob, editLinkedJob, getHiringBriefs, getLinkedJobs, setLinkedJobArchived, setLinkedJobStatus } from "@/services/phase2.service";
import type { HiringBrief, JobInput, LinkedJob } from "@/types/phase2.types";
import { useBusiness } from "../BusinessProvider";
import { requirementServiceLabel, useBusinessResource } from "../BusinessDashboardUI";
import { AdminGate, Badge, Empty, ErrorState, Heading, Loading, Pages, Refresh } from "./Phase2UI";
export function BusinessLinkedJobs({ id }: { id: string }) { const { user } = useBusiness(); return <JobWorkspace key={`${user.id}:${id}`} id={id} accountId={user.id} />; }
export function AdminLinkedJobs({ id }: { id?: string }) { return <AdminGate>{accountId => id ? <JobWorkspace key={`${accountId}:${id}`} id={id} accountId={accountId} admin /> : <HiringBriefs key={accountId} accountId={accountId} />}</AdminGate>; }
function HiringBriefs({ accountId }: { accountId: string }) {
  const [page, setPage] = useState(1), [search, setSearch] = useState(""), [query, setQuery] = useState(""), [version, setVersion] = useState(0);
  const request = useCallback((signal: AbortSignal) => getHiringBriefs(page, query, signal), [page, query]);
  const { data, loading, error } = useBusinessResource(`${accountId}:${page}:${query}:${version}`, request);
  return <div className="zb-att zb-p2 zb-hiring">
    <Heading eyebrow="HIRING OPERATIONS" title="Briefs, openings and applications. One flow." action={<Refresh loading={loading} onClick={() => setVersion(v => v + 1)} />}>Qualify business demand, publish the right opening, review every application and move suitable people into the business pipeline.</Heading>
    {data && <div className="zb-hiring-stats" aria-label="Hiring summary for this page"><article><BriefcaseBusiness aria-hidden="true" /><span>Visible briefs</span><strong>{data.summary.briefs}</strong></article><article><Send aria-hidden="true" /><span>Open roles</span><strong>{data.summary.open}</strong></article><article><FilePenLine aria-hidden="true" /><span>Draft roles</span><strong>{data.summary.drafts}</strong></article><article><UsersRound aria-hidden="true" /><span>Applications</span><strong>{data.summary.applications}</strong></article></div>}
    <form className="zb-p2-search zb-hiring-search" onSubmit={e => { e.preventDefault(); setQuery(search.trim()); setPage(1); }}><label><span>Company, service or reference</span><input value={search} maxLength={100} onChange={e => setSearch(e.target.value)} placeholder="Search hiring briefs" /></label><button className="zb-biz-button" type="submit">Search briefs</button></form>
    {loading ? <Loading /> : error ? <ErrorState admin error={error} retry={() => setVersion(v => v + 1)} /> : data && <>{!data.total ? <Empty title="No matching business briefs">Submitted business requirements will appear here. Try another search.</Empty> : <div className="zb-p2-cards zb-hiring-brief-grid">{data.items.map(item => <article className="zb-p2-card zb-hiring-brief" key={item.id}><div className="zb-hiring-card-top"><span className="zb-p2-card-icon"><BriefcaseBusiness aria-hidden="true" /></span><Badge value={item.status} /></div><h2>{requirementServiceLabel(item.serviceRequired)}</h2><p className="zb-hiring-company">{item.companyName}</p><p><MapPin aria-hidden="true" />{item.jobLocation}</p><dl><div><dt>Requested team</dt><dd>{item.workforceCount}</dd></div><div><dt>Open roles</dt><dd>{item.hiring?.open ?? 0}</dd></div><div><dt>Applications</dt><dd>{item.hiring?.applications ?? 0}</dd></div><div><dt>Drafts</dt><dd>{item.hiring?.draft ?? 0}</dd></div></dl>{Boolean(item.hiring?.archived) && <p className="zb-hiring-archive-note"><Archive aria-hidden="true" />{item.hiring?.archived} archived opening{item.hiring?.archived === 1 ? "" : "s"}</p>}<footer><Link className="zb-biz-text-link" href={`/admin/requirement-jobs/${item.id}`}>Manage hiring brief<ArrowUpRight aria-hidden="true" /></Link>{Boolean(item.hiring?.applications) && <Link className="zb-biz-text-link" href={`/admin/worker-applications?requirementId=${encodeURIComponent(item.id)}`}>Review applications<ArrowUpRight aria-hidden="true" /></Link>}</footer></article>)}</div>}<Pages page={data.page} totalPages={data.totalPages} onChange={setPage} /></>}
  </div>;
}
function JobWorkspace({ accountId, id, admin = false }: { accountId: string; id: string; admin?: boolean }) {
  const [page, setPage] = useState(1), [version, setVersion] = useState(0), [busy, setBusy] = useState(false), [notice, setNotice] = useState("");
  const [editor, setEditor] = useState<LinkedJob | "new" | null>(null); const opener = useRef<HTMLButtonElement | null>(null);
  const request = useCallback((signal: AbortSignal) => getLinkedJobs(admin, id, page, signal), [admin, id, page]);
  const { data, error, loading } = useBusinessResource(`${accountId}:${admin}:${id}:${page}:${version}`, request);
  const refresh = () => setVersion(v => v + 1);
  async function change(job: LinkedJob, status: LinkedJob["status"]) { if (busy || job.archivedAt) return; setBusy(true); setNotice(""); try { await setLinkedJobStatus(job, status); setNotice(status === "OPEN" ? "The opening is live on the Jobs page." : "The opening is closed to new applications."); refresh(); } catch (e) { setNotice(e instanceof Error ? e.message : "Job could not be updated."); } finally { setBusy(false); } }
  async function archive(job: LinkedJob, archived: boolean) { if (busy) return; setBusy(true); setNotice(""); try { await setLinkedJobArchived(job, archived); setNotice(archived ? "Opening archived. Its applications and history remain available." : "Opening restored as a draft. Review it before publishing again."); refresh(); } catch (e) { setNotice(e instanceof Error ? e.message : "Opening could not be archived."); } finally { setBusy(false); } }
  async function qualify() { if (busy || !data) return; setBusy(true); setNotice(""); try { await apiFetch(`/admin/requirement-jobs/${id}/qualify`, { method: "POST", headers: { "X-Requested-With": "XMLHttpRequest" }, body: JSON.stringify({ revision: data.requirement.revision }) }); refresh(); setNotice("Requirement qualified. Prepare a linked job opening below."); } catch (e) { setNotice(e instanceof Error ? e.message : "Requirement could not be updated."); } finally { setBusy(false); } }
  return <div className="zb-att zb-p2 zb-hiring">
    <Link className="zb-biz-text-link" href={admin ? "/admin/requirement-jobs" : `/business/requirements/${id}`}><ArrowLeft aria-hidden="true" />{admin ? "Hiring briefs" : "Requirement brief"}</Link>
    <Heading eyebrow="LINKED JOB OPENINGS" title="From requirement to reviewed people." action={<Refresh loading={loading} onClick={refresh} />}>{admin ? "Control publishing, review every applicant and hand suitable profiles into the business decision pipeline." : "See the openings our operations team has prepared for your requirement."}</Heading>
    {notice && <p className="zb-att-notice" role="status">{notice}</p>}
    {loading ? <Loading /> : error ? <ErrorState admin={admin} error={error} retry={refresh} /> : data && <>
      <section className="zb-p2-brief"><div><Badge value={data.requirement.status} /><h2>{data.requirement.companyName}</h2><p>{requirementServiceLabel(data.requirement.serviceRequired)} · {data.requirement.workforceCount} people · {data.requirement.jobLocation}</p><details><summary>Read the business brief</summary><p className="zb-att-preserve">{data.requirement.details}</p><p>{data.requirement.projectDuration} · {data.requirement.locations.join(", ")}</p></details></div>{admin && (data.requirement.status === "QUALIFIED" ? <button type="button" className="zb-biz-button" onClick={e => { opener.current = e.currentTarget; setEditor("new"); }}><Plus aria-hidden="true" />Prepare opening</button> : data.requirement.status !== "CLOSED" ? <button type="button" className="zb-biz-button" disabled={busy} onClick={() => void qualify()}><CheckCheck aria-hidden="true" />Mark brief qualified</button> : <p>Closed requirements cannot publish openings.</p>)}</section>
      <div className="zb-hiring-stats zb-hiring-stats--detail" aria-label="Opening and application summary"><article><BriefcaseBusiness aria-hidden="true" /><span>Total openings</span><strong>{data.summary.totalOpenings}</strong></article><article><Send aria-hidden="true" /><span>Live</span><strong>{data.summary.open}</strong></article><article><UsersRound aria-hidden="true" /><span>Applications</span><strong>{data.summary.applications}</strong></article><article><Archive aria-hidden="true" /><span>Archived</span><strong>{data.summary.archived}</strong></article></div>
      <div className="zb-hiring-flow" aria-label="Hiring workflow"><span><strong>01</strong>Publish opening</span><span><strong>02</strong>Review applications</span><span><strong>03</strong>Share suitable profiles</span><span><strong>04</strong>Business decision</span><span><strong>05</strong>Deployment</span></div>
      {!data.total ? <Empty title="No linked openings yet">{admin ? "Qualify the requirement, then prepare its first job opening." : "Our operations team will prepare openings after reviewing your requirement."}</Empty> : <div className="zb-p2-cards zb-hiring-job-grid">{data.items.map(job => { const archived = Boolean(job.archivedAt); return <article className={`zb-p2-card zb-hiring-job${archived ? " is-archived" : ""}`} key={job.id}><div className="zb-hiring-card-top"><Badge value={archived ? "ARCHIVED" : job.status} /><span className="zb-hiring-app-count"><UsersRound aria-hidden="true" />{job._count.applications}</span></div><h2>{job.title}</h2><p><MapPin aria-hidden="true" />{job.location}</p><div className="zb-p2-tags"><span>{job.engagementType}</span><span>{job.category}</span></div><p>{job.compensation || "Compensation to be discussed"}</p><details><summary>Opening content</summary><p className="zb-att-preserve">{job.description}</p><ul>{job.responsibilities.map((line, i) => <li key={i}>{line}</li>)}</ul><ul>{job.requirements.map((line, i) => <li key={i}>{line}</li>)}</ul></details><footer><div className="zb-hiring-links">{job.status === "OPEN" && !archived && <Link className="zb-biz-text-link" href={`/jobs/${job.slug}`}>Public opening<ArrowUpRight aria-hidden="true" /></Link>}{admin && <Link className="zb-biz-text-link" href={`/admin/worker-applications?jobId=${encodeURIComponent(job.id)}&requirementId=${encodeURIComponent(id)}`}>Review {job._count.applications ? `${job._count.applications} ` : ""}applications<ArrowUpRight aria-hidden="true" /></Link>}{admin && job._count.applications > 0 && <Link className="zb-biz-text-link" href={`/admin/candidate-management?requirementId=${encodeURIComponent(id)}`}>Business pipeline<ArrowUpRight aria-hidden="true" /></Link>}</div>{admin && <div className="zb-p2-actions">{archived ? <button type="button" className="zb-biz-button zb-biz-button--secondary" disabled={busy} onClick={() => void archive(job, false)}><RotateCcw aria-hidden="true" />Restore draft</button> : <><button type="button" className="zb-biz-button zb-biz-button--secondary" disabled={busy || data.requirement.status !== "QUALIFIED"} onClick={e => { opener.current = e.currentTarget; setEditor(job); }}><FilePenLine aria-hidden="true" />Edit</button><button type="button" className="zb-biz-button" disabled={busy || (job.status !== "OPEN" && data.requirement.status !== "QUALIFIED")} onClick={() => void change(job, job.status === "OPEN" ? "CLOSED" : "OPEN")}><Send aria-hidden="true" />{job.status === "OPEN" ? "Close" : "Publish"}</button><button type="button" className="zb-hiring-archive-button" disabled={busy} onClick={() => void archive(job, true)}><Archive aria-hidden="true" />Archive</button></>}</div>}</footer></article>; })}</div>}
      <Pages page={data.page} totalPages={data.totalPages} onChange={setPage} />
      {admin && <><div className="zb-hiring-next"><div><FileCheck2 aria-hidden="true" /><span><strong>Applications reviewed?</strong> Move suitable applicants into a business requirement only after the hiring team has reviewed them.</span></div><Link className="zb-biz-button zb-biz-button--secondary" href={`/admin/worker-applications?requirementId=${encodeURIComponent(id)}`}>Application desk<ArrowUpRight aria-hidden="true" /></Link><Link className="zb-biz-button" href={`/admin/candidate-management?requirementId=${encodeURIComponent(id)}`}>Candidate pipeline<ArrowUpRight aria-hidden="true" /></Link></div><Sheet open={editor !== null} onOpenChange={open => { if (!open) setEditor(null); }}><SheetContent className="zb-biz zb-att zb-p2 zb-p2-drawer" finalFocus={opener}><SheetHeader><SheetTitle>{editor === "new" ? "Prepare a public opening" : "Edit opening content"}</SheetTitle><SheetDescription>Write the role, location and candidate requirements. Save a draft before publishing.</SheetDescription></SheetHeader>{editor && <JobForm key={editor === "new" ? "new" : editor.id} requirement={data.requirement} job={editor === "new" ? undefined : editor} onSaved={() => { setEditor(null); refresh(); setNotice("Job draft saved. Review the content and choose Publish when ready."); }} />}</SheetContent></Sheet></>}
    </>}
  </div>;
}
function JobForm({ requirement, job, onSaved }: { requirement: HiringBrief; job?: LinkedJob; onSaved: () => void }) {
  const [values, setValues] = useState<JobInput>({ title: job?.title ?? "", city: job?.city ?? "", location: job?.location ?? requirement.jobLocation, state: job?.state ?? "", category: job?.category ?? "", engagementType: job?.engagementType ?? "Contract", description: job?.description ?? "", compensation: job?.compensation ?? "", responsibilities: job?.responsibilities ?? [], requirements: job?.requirements ?? [] });
  const [responsibilities, setResponsibilities] = useState(values.responsibilities.join("\n")), [requirements, setRequirements] = useState(values.requirements.join("\n"));
  const [busy, setBusy] = useState(false), [error, setError] = useState(""); const requestKey = useRef<string | null>(null);
  async function submit(e: FormEvent) { e.preventDefault(); if (busy) return; setBusy(true); setError(""); try {
    const input = { ...values, responsibilities: responsibilities.split("\n").map(line => line.trim()).filter(Boolean), requirements: requirements.split("\n").map(line => line.trim()).filter(Boolean) };
    requestKey.current ??= crypto.randomUUID(); if (job) await editLinkedJob(job, input); else await createLinkedJob(requirement.id, requirement.revision, requestKey.current, input); onSaved();
  } catch (e) { setError(e instanceof Error ? e.message : "Job could not be saved."); } finally { setBusy(false); } }
  return <form className="zb-att-form" onSubmit={submit}><fieldset disabled={busy}><div className="zb-att-form-grid">{([{ key: "title", label: "Job title", max: 160 }, { key: "city", label: "City", max: 120 }, { key: "location", label: "Work location", max: 180 }, { key: "state", label: "State (optional)", max: 120 }, { key: "category", label: "Job category", max: 120 }, { key: "engagementType", label: "Engagement type", max: 120 }, { key: "compensation", label: "Compensation (optional)", max: 300 }] as const).map(({ key, label, max }) => <label key={key}><span>{label}</span><input value={values[key]} required={key !== "state" && key !== "compensation"} minLength={key === "title" ? 3 : key === "state" || key === "compensation" ? undefined : 2} maxLength={max} onChange={e => setValues(v => ({ ...v, [key]: e.target.value }))} /></label>)}</div><label><span>Public job description *</span><textarea required minLength={30} maxLength={10000} rows={5} value={values.description} onChange={e => setValues(v => ({ ...v, description: e.target.value }))} /></label><label><span>Responsibilities · one per line</span><textarea rows={3} maxLength={15000} value={responsibilities} onChange={e => setResponsibilities(e.target.value)} /></label><label><span>Candidate requirements · one per line</span><textarea rows={3} maxLength={15000} value={requirements} onChange={e => setRequirements(e.target.value)} /></label>{error && <p role="alert" className="zb-biz-error">{error}</p>}<button className="zb-biz-button" type="submit">{busy ? "Saving…" : "Save job draft"}</button></fieldset></form>;
}
