"use client";
import Link from "next/link";
import { useCallback } from "react";
import { ArrowUpRight, BriefcaseBusiness, CalendarCheck2, FilePenLine, MapPin, MessageSquareMore, UsersRound } from "lucide-react";
import { getOperationsSummary } from "@/services/phase2.service";
import { useBusinessResource } from "../BusinessDashboardUI";
import { Empty, ErrorState, Loading, words } from "./Phase2UI";
export function OperationsOverview({ accountId, refreshToken }: { accountId: string; refreshToken: number }) {
  const request = useCallback((signal: AbortSignal) => getOperationsSummary(signal), []);
  const { data, error, loading } = useBusinessResource(`${accountId}:${refreshToken}`, request);
  return <section className="zb-att zb-p2 zb-p2-dashboard"><div className="zb-att-section-heading"><div><p className="zb-biz-eyebrow">YOUR EXECUTION WORKSPACE</p><h2>People, approvals and next actions.</h2></div><Link className="zb-biz-text-link" href="/business/reports">Explore reports<ArrowUpRight aria-hidden="true" /></Link></div>{loading ? <Loading /> : error ? <ErrorState admin={false} error={error} retry={() => window.location.reload()} /> : data && <><div className="zb-p2-metrics">{[{ label: "Active assignments today", value: data.active, detail: `${data.upcoming} upcoming assignments`, href: "/business/deployments", icon: MapPin }, { label: "Attendance pending review", value: data.approvals, detail: "All dates · open the oldest pending record", href: data.oldestPendingId ? `/business/attendance-approvals/${data.oldestPendingId}` : "/business/attendance-approvals", icon: CalendarCheck2 }, { label: "Open corrections", value: data.corrections, detail: "Awaiting operations review", href: "/business/attendance?tab=corrections", icon: MessageSquareMore }, { label: "Selected candidates", value: data.candidates.find(row => row.status === "SELECTED")?.count ?? 0, detail: "Current shared profiles", href: "/business/candidates", icon: UsersRound }, { label: "Published linked jobs", value: data.jobs, detail: "Across your requirements", href: "/business/requirements", icon: BriefcaseBusiness }, { label: "Saved drafts", value: data.drafts, detail: "Ready to continue", href: "/business/requirements/drafts", icon: FilePenLine }].map(({ label, value, detail, href, icon: Icon }) => <article key={label}><Icon aria-hidden="true" /><strong>{value}</strong><span>{label}</span><small>{detail}</small><Link href={href} aria-label={`Open ${label.toLowerCase()}`}>Open view<ArrowUpRight aria-hidden="true" /></Link></article>)}</div>{data.candidates.length ? <div className="zb-p2-pipeline" aria-label="Current candidate pipeline">{data.candidates.map(row => <Link href="/business/candidates" key={row.status}><span>{words(row.status)}</span><strong>{row.count}</strong></Link>)}</div> : <Empty title="Your candidate pipeline starts here">Shared candidates, assignments and attendance reviews will appear as your requirement progresses.</Empty>}<p className="zb-p2-note">Current workspace totals include all dates. Reports provide period and location filters. Attendance recording and approval are separate steps.</p></>}</section>;
}
