"use client";
import Link from "next/link";
import { useRef, useState } from "react";
import { ArrowUpRight, Banknote, CalendarRange, Download, FileText, Printer, ReceiptIndianRupee, WalletCards } from "lucide-react";
import { ApiError } from "@/lib/api";
import type { EarningsList, EarningsStatement } from "@/types/worker-finance.types";
import { WorkerAlert, WorkerEmpty, WorkerHeading, workerError } from "./WorkerUI";
import { dateLabel, Pagination, ReadState, Status, useWorkflowRead, WorkflowBack } from "./WorkflowUI";

export const money = (paise: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(paise / 100);
export function WorkerEarnings() {
  const [page, setPage] = useState(1), [assignmentId, setAssignmentId] = useState(""), [from, setFrom] = useState(""), [to, setTo] = useState("");
  const params = new URLSearchParams({ page: String(page), ...(assignmentId ? { assignmentId } : {}), ...(from ? { from } : {}), ...(to ? { to } : {}) });
  const read = useWorkflowRead<EarningsList>(`/workers/earnings?${params}`);
  return <><section className="zwf-banner"><span className="zw-icon"><WalletCards aria-hidden="true" /></span><WorkerHeading eyebrow="EARNINGS" title="Know exactly what was approved and paid." copy="Review approved earnings statements, allowances, reimbursements, deductions and operations-recorded payments. Amounts here are records, not a payment-transfer service." /></section>
    {read.data && <section className="zwe-summary" aria-label="Earnings totals"><MoneyCard icon={Banknote} label="Approved earnings" value={read.data.summary.approvedPaise} /><MoneyCard icon={ReceiptIndianRupee} label="Payments recorded" value={read.data.summary.paidPaise} /><MoneyCard icon={WalletCards} label="Outstanding balance" value={read.data.summary.outstandingPaise} /></section>}
    <form className="zwe-filters" onSubmit={event => event.preventDefault()}><label className="zw-field"><span>Assignment</span><select value={assignmentId} onChange={event => { setAssignmentId(event.target.value); setPage(1); }}><option value="">All assignments</option>{read.data?.assignments.map(item => <option key={item.id} value={item.id}>{item.role} · {item.company}</option>)}</select></label><label className="zw-field"><span>Period from</span><input type="date" value={from} onChange={event => { setFrom(event.target.value); setPage(1); }} /></label><label className="zw-field"><span>Period to</span><input type="date" value={to} onChange={event => { setTo(event.target.value); setPage(1); }} /></label><button type="button" className="zw-button zw-button--secondary" onClick={() => { setAssignmentId(""); setFrom(""); setTo(""); setPage(1); }}>Clear filters</button></form>
    <ReadState {...read}>{read.data?.items.length ? <div className="zwe-list">{read.data.items.map(item => <StatementCard key={item.id} item={item} />)}</div> : <WorkerEmpty icon={WalletCards} title="No approved earnings yet" copy="Approved earnings statements appear here after attendance has been reviewed and operations approves the statement." href="/worker/assignments" label="View assignments" />}{read.data && <Pagination {...read.data} change={setPage} />}</ReadState></>;
}
function MoneyCard({ icon: Icon, label, value }: { icon: typeof Banknote; label: string; value: number }) { return <article className="zw-card"><span className="zw-icon"><Icon aria-hidden="true" /></span><div><span>{label}</span><strong>{money(value)}</strong></div></article>; }
function StatementCard({ item }: { item: EarningsStatement }) { return <article className="zw-card zwe-statement"><div className="zwe-statement-top"><div><p className="zw-eyebrow">{item.assignment.company}</p><h2>{item.assignment.role}</h2><p>{item.assignment.location}</p></div><Status value={item.totals.paymentStatus} /></div><div className="zwe-period"><CalendarRange aria-hidden="true" /><span>{dateLabel(item.periodStart)} – {dateLabel(item.periodEnd)}</span></div><div className="zwe-mini-money"><div><span>Net payable</span><strong>{money(item.totals.netPayablePaise)}</strong></div><div><span>Paid</span><strong>{money(item.totals.paidPaise)}</strong></div><div><span>Outstanding</span><strong>{money(item.totals.outstandingPaise)}</strong></div></div><Link className="zw-button zw-button--secondary" href={`/worker/earnings/${item.id}`}>Statement details<ArrowUpRight aria-hidden="true" /></Link></article>; }
export function WorkerEarningsDetail({ id }: { id: string }) {
  const read = useWorkflowRead<EarningsStatement>(`/workers/earnings/${id}`);
  return <><WorkflowBack href="/worker/earnings">Earnings history</WorkflowBack><ReadState {...read}>{read.data && <StatementDetail item={read.data} />}</ReadState></>;
}
function StatementDetail({ item }: { item: EarningsStatement }) {
  const [error, setError] = useState(""), lock = useRef(false);
  async function csv() { if (lock.current) return; lock.current = true; setError(""); try { const response = await fetch(`/api/backend/workers/earnings/${item.id}/csv`, { credentials: "include", cache: "no-store" }); if (!response.ok) throw new ApiError("The statement CSV could not be downloaded.", response.status); const url = URL.createObjectURL(await response.blob()); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `earnings-${item.periodStart}-${item.periodEnd}.csv`; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 10_000); } catch (caught) { setError(workerError(caught)); } finally { lock.current = false; } }
  return <div className="zwe-detail"><section className="zwf-banner"><div><p className="zw-eyebrow">APPROVED STATEMENT</p><h1>{item.assignment.role}</h1><p>{item.assignment.company} · {item.assignment.location}</p><p>{dateLabel(item.periodStart)} – {dateLabel(item.periodEnd)}</p></div><Status value={item.totals.paymentStatus} /></section><div className="zwe-print-actions"><button type="button" className="zw-button zw-button--secondary" onClick={() => window.print()}><Printer aria-hidden="true" />Print statement</button><button type="button" className="zw-button" onClick={csv}><Download aria-hidden="true" />Download CSV</button></div><WorkerAlert message={error} />
    <section className="zwe-summary"><MoneyCard icon={Banknote} label="Net payable" value={item.totals.netPayablePaise} /><MoneyCard icon={ReceiptIndianRupee} label="Paid" value={item.totals.paidPaise} /><MoneyCard icon={WalletCards} label="Outstanding" value={item.totals.outstandingPaise} /></section>
    <div className="zwe-detail-grid"><section className="zw-card"><h2>Earnings breakdown</h2><div className="zwe-ledger">{item.lines?.map(line => <div key={line.id}><span><strong>{line.label}</strong><small>{line.reason || line.type.replaceAll("_", " ").toLowerCase()}</small></span><strong className={line.type === "DEDUCTION" ? "is-debit" : ""}>{line.type === "DEDUCTION" ? "−" : "+"}{money(line.amountPaise)}</strong></div>)}</div>{item.adjustments?.length ? <><h3>Approved adjustments</h3><div className="zwe-ledger">{item.adjustments.map(adjustment => <div key={adjustment.id}><span><strong>{adjustment.type === "CREDIT" ? "Credit adjustment" : "Debit adjustment"}</strong><small>{adjustment.reason} · {dateLabel(adjustment.createdAt)}</small></span><strong className={adjustment.type === "DEBIT" ? "is-debit" : ""}>{adjustment.type === "DEBIT" ? "−" : "+"}{money(adjustment.amountPaise)}</strong></div>)}</div></> : null}<div className="zwe-total"><span>Net payable</span><strong>{money(item.totals.netPayablePaise)}</strong></div></section>
      <section className="zw-card"><h2>Payment history</h2>{item.payments?.length ? <div className="zwe-payments">{item.payments.map(payment => <article key={payment.id} className={payment.status === "VOIDED" ? "is-void" : ""}><div><strong>{money(payment.amountPaise)}</strong><Status value={payment.status} /></div><p>{dateLabel(payment.paidAt)} · {payment.method}</p><p>Reference: {payment.reference}</p>{payment.note && <small>{payment.note}</small>}{payment.voidReason && <small>Voided: {payment.voidReason}</small>}</article>)}</div> : <p className="zw-info">No payment has been recorded against this approved statement yet.</p>}<div className="zwe-total"><span>Balance outstanding</span><strong>{money(item.totals.outstandingPaise)}</strong></div></section>
    </div><section className="zw-card zwe-note"><FileText aria-hidden="true" /><div><h2>Approval record</h2><p>{item.approvalNote || "Approved by operations."}</p><small>{item.approvedAt ? `Approved ${dateLabel(item.approvedAt)}` : "Approval timestamp unavailable"}</small></div></section></div>;
}
