"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { ArrowUpRight, BriefcaseBusiness, CheckCircle2, Download, FileText, GraduationCap, MapPin, Plus, Save, Sparkles, Trash2, Upload, UserRound, type LucideIcon } from "lucide-react";
import { downloadWorkerResume, getWorkerProfile, removeWorkerResume, saveWorkerProfile, uploadWorkerResume } from "@/services/worker.service";
import type { WorkerProfile, WorkerProfileInput } from "@/types/worker.types";
import { useWorker } from "./WorkerProvider";
import { listFields, useWorkerDraft, type ListField } from "./WorkerDraft";
import { WorkerAlert, WorkerHeading, WorkerProgress, workerError } from "./WorkerUI";

function profileInput(profile: WorkerProfile | null, phone: string | null): WorkerProfileInput {
  return { revision: profile?.revision ?? 0, fullName: profile?.fullName ?? "", phone: profile?.phone ?? phone ?? "", headline: profile?.headline ?? "", about: profile?.about ?? "", city: profile?.city ?? "", state: profile?.state ?? "", postalCode: profile?.postalCode ?? "", skills: profile?.skills ?? [], languages: profile?.languages ?? [], experienceYears: profile?.experienceYears ?? null, education: profile?.education ?? [], workExperience: profile?.workExperience ?? [], preferredLocations: profile?.preferredLocations ?? [], preferredCategories: profile?.preferredCategories ?? [], preferredEngagements: profile?.preferredEngagements ?? [], availability: profile?.availability ?? "", isAvailable: profile?.isAvailable ?? true, consent: Boolean(profile?.consentAt) };
}
const listValues = (values: WorkerProfileInput) => Object.fromEntries(listFields.map(field => [field, values[field].join(", ")])) as Record<ListField, string>;
const splitList = (value: string) => [...new Set(value.split(",").map(item => item.trim()).filter(Boolean))];
function SectionTitle({ icon: Icon, number, title, copy }: { icon: LucideIcon; number: string; title: string; copy: string }) { return <div className="zw-section-title"><span className="zw-icon"><Icon aria-hidden="true" /></span><div><p className="zw-eyebrow">{number}</p><h2>{title}</h2><p>{copy}</p></div></div>; }

export function WorkerProfileForm() {
  const { profile, user, completion, updateProfile } = useWorker(); const { draft, setDraft } = useWorkerDraft();
  const [values, setValues] = useState(() => draft?.values ?? profileInput(profile, user.phone));
  const [lists, setLists] = useState(() => draft?.lists ?? listValues(profileInput(profile, user.phone)));
  const [savedSnapshot, setSavedSnapshot] = useState(() => JSON.stringify({ values: profileInput(profile, user.phone), lists: listValues(profileInput(profile, user.phone)) }));
  const [busy, setBusy] = useState(false); const [fileBusy, setFileBusy] = useState(false);
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [fileError, setFileError] = useState(""); const [fileMessage, setFileMessage] = useState("");
  const [file, setFile] = useState<File | null>(null); const upload = useRef<HTMLInputElement>(null);
  const dirty = JSON.stringify({ values, lists }) !== savedSnapshot;
  useEffect(() => { setDraft(dirty ? { values, lists } : null); }, [dirty, values, lists, setDraft]);
  useEffect(() => {
    if (!dirty) return;
    const warn = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ""; };
    window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn);
  }, [dirty]);
  function change<K extends keyof WorkerProfileInput>(key: K, value: WorkerProfileInput[K]) { setValues(current => ({ ...current, [key]: value })); setMessage(""); }
  function field(key: "fullName" | "phone" | "headline" | "city" | "state" | "postalCode", label: string, options: { autoComplete?: string; maxLength?: number; required?: boolean; placeholder?: string } = {}) {
    return <label className="zw-field"><span>{label}{options.required ? " *" : ""}</span><input type={key === "phone" ? "tel" : "text"} inputMode={key === "postalCode" ? "numeric" : undefined} value={values[key]} onChange={event => change(key, event.target.value)} {...options} /></label>;
  }
  function tags(key: ListField, label: string, placeholder: string, hint: string) { return <div className="zw-field"><label htmlFor={`worker-${key}`}>{label}</label><input id={`worker-${key}`} value={lists[key]} maxLength={1800} placeholder={placeholder} aria-describedby={`worker-${key}-hint`} onChange={event => { setLists(current => ({ ...current, [key]: event.target.value })); setMessage(""); }} /><small id={`worker-${key}-hint`}>{hint} Separate entries with commas.</small><div className="zw-tags" aria-hidden="true">{splitList(lists[key]).slice(0, 8).map(item => <span key={item}>{item}</span>)}</div></div>; }
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (busy) return; setBusy(true); setError(""); setMessage("");
    try {
      const payload = { ...values, ...Object.fromEntries(listFields.map(key => [key, splitList(lists[key])])) };
      const result = await saveWorkerProfile(payload); updateProfile(result.data);
      const stored = profileInput(result.data.profile, user.phone); const storedLists = listValues(stored);
      setValues(stored); setLists(storedLists); setSavedSnapshot(JSON.stringify({ values: stored, lists: storedLists })); setDraft(null);
      setMessage("Your profile is saved. You can keep exploring opportunities.");
    } catch (caught) { setError(workerError(caught)); }
    finally { setBusy(false); }
  }
  async function reload() {
    setBusy(true); setError("");
    try { const result = await getWorkerProfile(); updateProfile(result.data); const stored = profileInput(result.data.profile, user.phone); const storedLists = listValues(stored); setValues(stored); setLists(storedLists); setSavedSnapshot(JSON.stringify({ values: stored, lists: storedLists })); setDraft(null); setMessage("The saved profile has been loaded."); }
    catch (caught) { setError(workerError(caught)); } finally { setBusy(false); }
  }
  async function fileAction(action: "upload" | "download" | "remove" | "refresh") {
    if (fileBusy) return; setFileError(""); setFileMessage("");
    if (action === "upload" && (!file || !file.name.toLowerCase().endsWith(".pdf") || file.size === 0 || file.size > 2 * 1024 * 1024)) { setFileError("Choose a non-empty PDF resume of 2 MB or smaller."); return; }
    setFileBusy(true);
    try {
      if (action === "download") {
        const blob = await downloadWorkerResume(); const href = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = href; anchor.download = profile?.resume?.fileName || "resume.pdf"; document.body.append(anchor); anchor.click(); anchor.remove(); window.setTimeout(() => URL.revokeObjectURL(href), 1000);
      } else {
        const result = action === "upload" ? await uploadWorkerResume(file!, profile?.resumeRevision ?? 0) : action === "remove" ? await removeWorkerResume(profile?.resumeRevision ?? 0) : await getWorkerProfile();
        updateProfile(result.data); setFile(null); if (upload.current) upload.current.value = "";
        setFileMessage(action === "upload" ? "Your resume has been saved privately." : action === "remove" ? "Your resume has been removed." : "Resume details refreshed. Your unfinished profile edits are still here.");
      }
    } catch (caught) { setFileError(workerError(caught)); }
    finally { setFileBusy(false); }
  }
  return <><div className="zw-page-intro"><WorkerHeading eyebrow="MY PROFILE & CV" title="Show what you bring to the work." copy="Build your profile one section at a time. Your saved details stay with your worker account." /><Link className="zw-button zw-button--secondary" href="/worker/jobs">Explore jobs<ArrowUpRight aria-hidden="true" /></Link></div>
    <div className="zw-profile-layout"><div><form onSubmit={save}>
      <WorkerAlert message={error} />{error && <button className="zw-text-button" type="button" onClick={reload} disabled={busy}>Discard unsaved edits and reload saved profile</button>}{message && <p className="zw-success" role="status"><CheckCircle2 aria-hidden="true" />{message}</p>}
      <section className="zw-card zw-profile-section" id="personal"><SectionTitle number="01 / THE BASICS" icon={UserRound} title="Introduce yourself" copy="Make it easy to understand who you are and where you work." /><div className="zw-fields">{field("fullName", "Full name", { required: true, maxLength: 120, autoComplete: "name" })}{field("phone", "Phone number", { required: true, maxLength: 24, autoComplete: "tel" })}<label className="zw-field"><span>Verified email</span><input value={user.email} readOnly autoComplete="email" /><small>Your sign-in email is managed separately from your profile.</small></label>{field("headline", "Professional headline", { maxLength: 100, placeholder: "e.g. Field sales executive · Retail" })}{field("city", "City", { maxLength: 120, autoComplete: "address-level2" })}{field("state", "State", { maxLength: 120, autoComplete: "address-level1" })}{field("postalCode", "PIN code", { maxLength: 6, autoComplete: "postal-code" })}<label className="zw-field"><span>Years of experience</span><input type="number" min={0} max={60} step={1} value={values.experienceYears ?? ""} onChange={event => change("experienceYears", event.target.value === "" ? null : Number(event.target.value))} /><small>Enter 0 if you are starting your career.</small></label></div><label className="zw-field"><span>About you</span><textarea rows={3} maxLength={1200} placeholder="The work you enjoy, strengths you bring and what you would like to do next…" value={values.about} onChange={event => change("about", event.target.value)} /></label></section>
      <section className="zw-card zw-profile-section" id="education"><SectionTitle number="02 / YOUR FOUNDATION" icon={GraduationCap} title="Education" copy="Add your qualifications, training or institution details." />{values.education.length === 0 && <p className="zw-inline-empty">No education added yet. Start with your most recent qualification.</p>}{values.education.map((item, index) => <fieldset className="zw-record" key={index}><legend>Education {index + 1}</legend><div className="zw-fields"><label className="zw-field"><span>Qualification *</span><input required minLength={2} maxLength={120} value={item.qualification} onChange={event => change("education", values.education.map((value, i) => i === index ? { ...value, qualification: event.target.value } : value))} /></label><label className="zw-field"><span>Institution *</span><input required minLength={2} maxLength={160} value={item.institution} onChange={event => change("education", values.education.map((value, i) => i === index ? { ...value, institution: event.target.value } : value))} /></label><label className="zw-field"><span>Completion year *</span><input required type="number" min={1950} max={new Date().getFullYear() + 6} value={item.year || ""} onChange={event => change("education", values.education.map((value, i) => i === index ? { ...value, year: Number(event.target.value) } : value))} /></label></div><button className="zw-text-button" type="button" onClick={() => change("education", values.education.filter((_, i) => i !== index))}><Trash2 aria-hidden="true" />Remove education {index + 1}</button></fieldset>)}<button type="button" className="zw-button zw-button--secondary" disabled={values.education.length >= 8} onClick={() => change("education", [...values.education, { qualification: "", institution: "", year: new Date().getFullYear() }])}><Plus aria-hidden="true" />Add education</button></section>
      <section className="zw-card zw-profile-section" id="experience"><SectionTitle number="03 / YOUR EXPERIENCE" icon={BriefcaseBusiness} title="The work you’ve done" copy="Starting out? Enter 0 years above. You can also include internships and short assignments." />{values.workExperience.length === 0 && <p className="zw-inline-empty">Your experience will appear here when you add it.</p>}{values.workExperience.map((item, index) => {
        const update = (data: Partial<typeof item>) => change("workExperience", values.workExperience.map((value, i) => i === index ? { ...value, ...data } : value));
        return <fieldset className="zw-record" key={index}><legend>Experience {index + 1}</legend><div className="zw-fields"><label className="zw-field"><span>Company *</span><input required minLength={2} maxLength={160} value={item.company} onChange={event => update({ company: event.target.value })} /></label><label className="zw-field"><span>Role *</span><input required minLength={2} maxLength={120} value={item.role} onChange={event => update({ role: event.target.value })} /></label><label className="zw-field"><span>Start month *</span><input required type="month" min="1950-01" max={new Date().toISOString().slice(0, 7)} value={item.startMonth} onChange={event => update({ startMonth: event.target.value })} /></label><label className="zw-field"><span>End month{!item.current ? " *" : ""}</span><input type="month" required={!item.current} disabled={item.current} min={item.startMonth || "1950-01"} max={new Date().toISOString().slice(0, 7)} value={item.endMonth ?? ""} onChange={event => update({ endMonth: event.target.value || null })} /></label></div><label className="zw-check"><input type="checkbox" checked={item.current} onChange={event => update({ current: event.target.checked, endMonth: null })} /><span>I currently work here</span></label><label className="zw-field"><span>What you did</span><textarea rows={2} maxLength={600} value={item.description} onChange={event => update({ description: event.target.value })} /></label><button className="zw-text-button" type="button" onClick={() => change("workExperience", values.workExperience.filter((_, i) => i !== index))}><Trash2 aria-hidden="true" />Remove experience {index + 1}</button></fieldset>;
      })}<button type="button" className="zw-button zw-button--secondary" disabled={values.workExperience.length >= 10} onClick={() => change("workExperience", [...values.workExperience, { company: "", role: "", startMonth: "", endMonth: null, current: false, description: "" }])}><Plus aria-hidden="true" />Add experience</button></section>
      <section className="zw-card zw-profile-section" id="skills"><SectionTitle number="04 / WHAT YOU DO WELL" icon={Sparkles} title="Skills & languages" copy="Give your practical strengths a place in your profile." />{tags("skills", "Your skills", "Sales, customer service, data collection", "Up to 20 skills.")}{tags("languages", "Languages you speak", "Hindi, English", "Up to 10 languages.")}</section>
      <section className="zw-card zw-profile-section" id="preferences"><SectionTitle number="05 / WHAT FITS YOUR LIFE" icon={MapPin} title="Work preferences" copy="Describe the locations and types of work you are looking for." />{tags("preferredLocations", "Preferred locations", "Delhi, Ghazipur", "Up to 10 locations.")}{tags("preferredCategories", "Preferred work categories", "Field work, sales, operations", "Up to 10 categories.")}{tags("preferredEngagements", "Preferred work types", "Full-time, contract, gig", "Up to 10 types.")}<label className="zw-field"><span>When can you start?</span><input list="worker-availability-options" maxLength={80} value={values.availability} placeholder="Choose or enter your availability" onChange={event => change("availability", event.target.value)} /><datalist id="worker-availability-options"><option value="Immediately" /><option value="Within 15 days" /><option value="Within 30 days" /><option value="After a notice period" /></datalist></label><label className="zw-check"><input type="checkbox" checked={values.isAvailable} onChange={event => change("isAvailable", event.target.checked)} /><span>I am currently available for work opportunities.</span></label></section>
      <div className="zw-card zw-save-profile"><label className="zw-check"><input type="checkbox" required checked={values.consent} onChange={event => change("consent", event.target.checked)} /><span>I confirm that these details can be stored in my ZOBHUNGER worker profile.</span></label><div className="zw-save-bar"><p role="status">{dirty ? "Unsaved changes · Kept while you browse this worker space" : "Showing your saved profile"}</p><button className="zw-button" disabled={busy || !dirty}><Save aria-hidden="true" />{busy ? "Saving…" : "Save profile"}</button></div></div>
    </form><section className="zw-card zw-profile-section" id="resume"><SectionTitle number="06 / YOUR STORY ON FILE" icon={FileText} title="Your CV / resume" copy="Upload a PDF up to 2 MB. Your file is private to your worker account." /><WorkerAlert message={fileError} />{fileMessage && <p className="zw-success" role="status">{fileMessage}</p>}{profile?.resume ? <div className="zw-resume-file"><span className="zw-icon"><FileText aria-hidden="true" /></span><div><strong>{profile.resume.fileName}</strong><small>{Math.ceil(profile.resume.size / 1024)} KB · PDF</small></div><button className="zw-icon-button" type="button" aria-label="Download your resume" disabled={fileBusy} onClick={() => fileAction("download")}><Download aria-hidden="true" /></button><button className="zw-icon-button" type="button" aria-label="Remove your resume" disabled={fileBusy} onClick={() => fileAction("remove")}><Trash2 aria-hidden="true" /></button></div> : <p className="zw-inline-empty">No resume uploaded yet.</p>}<label className="zw-upload"><Upload aria-hidden="true" /><span>{profile?.resume ? "Choose a replacement PDF" : "Choose your PDF resume"}</span><input ref={upload} type="file" accept="application/pdf,.pdf" disabled={fileBusy} onChange={event => { setFile(event.target.files?.[0] ?? null); setFileError(""); setFileMessage(""); }} /><small>{file ? file.name : "PDF only · maximum 2 MB"}</small></label><div className="zw-actions"><button type="button" className="zw-button" disabled={fileBusy || !file} onClick={() => fileAction("upload")}><Upload aria-hidden="true" />{fileBusy ? "Please wait…" : "Upload resume"}</button><button type="button" className="zw-text-button" disabled={fileBusy} onClick={() => fileAction("refresh")}>Refresh resume details</button></div></section></div>
    <aside className="zw-profile-rail"><WorkerProgress completion={completion} /><div className="zw-profile-photo"><Image src="/images/careers/field-opportunities-600.webp" alt="ZOBHUNGER field executives reviewing a tablet in a market" width={600} height={400} sizes="(max-width: 950px) 100vw, 300px" /><div><p className="zw-eyebrow">YOUR NEXT CHAPTER</p><h2>Bring your experience to the field.</h2><p>A clear profile helps you prepare for the roles you want.</p><Link href="/worker/jobs">Find work<ArrowUpRight aria-hidden="true" /></Link></div></div></aside></div>
  </>;
}
