"use client";

import Link from "next/link";
import { useCallback, useRef, useState, type FormEvent } from "react";
import { ArrowLeft, ArrowUpRight, BarChart3, CalendarClock, CalendarDays, CheckCheck, ChevronLeft, ChevronRight, Flag, LayoutGrid, MapPin, Plus, RefreshCw, SlidersHorizontal, UserRoundCheck, UsersRound } from "lucide-react";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { deploymentHref, getDeploymentRoster } from "@/services/deployments.service";
import { deploymentStates, type DeploymentQuery, type DeploymentView, type RosterAssignment } from "@/types/deployments.types";
import { useBusiness } from "../BusinessProvider";
import { businessDate, requirementServiceLabel, useBusinessResource } from "../BusinessDashboardUI";
import { AttendanceLoading, AttendancePages, clock, todayIST } from "../attendance/AttendanceUI";
import { NewAssignment } from "../attendance/AssignmentManager";
import { DeploymentBadge, DeploymentError, deploymentLabels, moveDate, WeekSchedule } from "./DeploymentUI";
import { DeploymentProgress } from "./DeploymentProgress";
import "@/styles/business-attendance.css";
import "@/styles/business-deployments.css";

export function BusinessDeployments(props: { requirementId?: string; initialDate?: string; initialView?: string }) {
  const { user } = useBusiness();
  return <DeploymentWorkspace key={`${user.id}:${props.requirementId ?? "all"}`} accountId={user.id} {...props} />;
}
export function DeploymentWorkspace({ accountId, admin = false, requirementId, initialDate, initialView }: { accountId: string; admin?: boolean; requirementId?: string; initialDate?: string; initialView?: string }) {
  const [view, setView] = useState<DeploymentView | "progress">(["locations", "schedule", "progress"].includes(initialView ?? "") ? initialView as DeploymentView | "progress" : "roster");
  const [adding, setAdding] = useState(false); const [version, setVersion] = useState(0); const [receipt, setReceipt] = useState<{ id: string; created: boolean } | null>(null);
  return <div className="zb-att zb-deploy">
    {requirementId && !admin && <Link className="zb-biz-text-link" href={`/business/requirements/${requirementId}`}><ArrowLeft aria-hidden="true" />Back to requirement</Link>}
    <header className="zb-deploy-heading"><div><p className="zb-biz-eyebrow">DEPLOYMENT & TEAM ROSTER</p><h1>{admin ? "Turn selections into a ready team." : "Your people. Your places. One clear plan."}</h1><p>{admin ? "Confirm the person, place and schedule. Keep every assignment connected to the business requirement." : "See who is assigned, where they will work and how the week is planned."}</p></div><div className="zb-deploy-heading-actions">{admin ? <Sheet open={adding} onOpenChange={setAdding}><SheetTrigger className="zb-biz-button"><Plus aria-hidden="true" />New assignment</SheetTrigger><SheetContent className="zb-biz zb-att zb-deploy zb-deploy-setup-drawer"><SheetHeader><SheetTitle>Confirm a team assignment</SheetTitle><SheetDescription>Choose a selected candidate, then set the location, supervisor, dates and shift.</SheetDescription></SheetHeader><div className="zb-deploy-drawer-body">{adding && <NewAssignment key={`${accountId}:${version}`} module="deployments" accountId={accountId} onSaved={result => { setReceipt(result); setAdding(false); setVersion(value => value + 1); }} />}</div></SheetContent></Sheet> : <Link className="zb-biz-button zb-biz-button--secondary" href="/business/requirements">Your requirements<ArrowUpRight aria-hidden="true" /></Link>}</div></header>
    <ol className="zb-deploy-story"><li><span><UserRoundCheck aria-hidden="true" /></span><div><strong>01 / Confirm the person</strong><p>Selected for your requirement</p></div></li><li><span><MapPin aria-hidden="true" /></span><div><strong>02 / Set the workplace</strong><p>Location and supervisor in place</p></div></li><li><span><CalendarDays aria-hidden="true" /></span><div><strong>03 / Plan the week</strong><p>Dates, shifts and working days</p></div></li></ol>
    {receipt && <div className="zb-att-success" role="status"><CheckCheck aria-hidden="true" /><span>{receipt.created ? "Assignment confirmed." : "This candidate already has an assignment. Its details were preserved."} <Link href={deploymentHref(admin, receipt.id)}>Open assignment<ArrowUpRight aria-hidden="true" /></Link></span></div>}
    <div className="zb-deploy-tabs" role="group" aria-label="Deployment views">{[{ value: "roster", label: "Team roster", icon: LayoutGrid }, { value: "locations", label: "By location", icon: MapPin }, { value: "schedule", label: "Weekly schedule", icon: CalendarDays }, { value: "progress", label: "Deployment progress", icon: BarChart3 }].map(({ value, label, icon: Icon }) => <button type="button" key={value} aria-pressed={view === value} onClick={() => setView(value as typeof view)}><Icon aria-hidden="true" />{label}</button>)}</div>
    {view === "progress" ? <DeploymentProgress key={`${accountId}:${requirementId ?? "all"}:${version}`} accountId={accountId} admin={admin} requirementId={requirementId} initialDate={initialDate} /> : <TeamRoster key={`${accountId}:${requirementId ?? "all"}`} accountId={accountId} admin={admin} requirementId={requirementId} initialDate={initialDate} view={view} refreshToken={version} />}
    <p className="zb-att-footnote"><CalendarClock aria-hidden="true" />Schedules use IST and the latest saved assignment dates. Actual check-in and check-out records are available in Attendance.</p>
  </div>;
}

function TeamRoster({ accountId, admin, requirementId, initialDate, view, refreshToken }: { accountId: string; admin: boolean; requirementId?: string; initialDate?: string; view: DeploymentView; refreshToken: number }) {
  const initial = { date: initialDate || todayIST(), query: "", location: "", status: "ALL" as DeploymentQuery["status"] };
  const [filters, setFilters] = useState(initial); const [draft, setDraft] = useState(initial); const [page, setPage] = useState(1); const [version, setVersion] = useState(0); const [open, setOpen] = useState(false);
  const trigger = useRef<HTMLButtonElement | null>(null);
  const request = useCallback((signal: AbortSignal) => getDeploymentRoster(admin, { ...filters, view, page, requirementId }, signal), [admin, filters, view, page, requirementId]);
  const { data, loading, error } = useBusinessResource(JSON.stringify({ accountId, admin, filters, view, page, requirementId, version, refreshToken }), request);
  function apply(event: FormEvent) { event.preventDefault(); setFilters({ ...draft, query: draft.query.trim(), location: draft.location.trim() }); setPage(1); setOpen(false); }
  function moveWeek(days: number) { const date = moveDate(filters.date, days); if (date >= "2000-01-01" && date <= "2099-12-31") { setFilters(value => ({ ...value, date })); setDraft(value => ({ ...value, date })); setPage(1); } }
  const form = <form className="zb-deploy-filters" onSubmit={apply}><label><span>Reference date (IST)</span><input type="date" required min="2000-01-01" max="2099-12-31" value={draft.date} onChange={e => setDraft(value => ({ ...value, date: e.target.value }))} /></label><label><span>Person, role or supervisor</span><input value={draft.query} maxLength={100} placeholder={admin ? "Name, role or company" : "Search the team"} onChange={e => setDraft(value => ({ ...value, query: e.target.value }))} /></label><label><span>Work location</span><input value={draft.location} maxLength={100} placeholder="Site or city" onChange={e => setDraft(value => ({ ...value, location: e.target.value }))} /></label><label><span>Assignment status</span><select value={draft.status} onChange={e => setDraft(value => ({ ...value, status: e.target.value as typeof value.status }))}><option value="ALL">All statuses</option>{deploymentStates.map(state => <option key={state} value={state}>{deploymentLabels[state].label}</option>)}</select></label><button className="zb-biz-button" type="submit">Apply filters</button></form>;
  return <section aria-label="Team roster"><div className="zb-deploy-toolbar"><div className="zb-deploy-mobile-filter"><Sheet open={open} onOpenChange={setOpen}><SheetTrigger className="zb-biz-button zb-biz-button--secondary" ref={trigger}><SlidersHorizontal aria-hidden="true" />Filters</SheetTrigger><SheetContent className="zb-biz zb-att zb-deploy zb-deploy-filter-drawer" finalFocus={trigger}><SheetHeader><SheetTitle>Filter team assignments</SheetTitle><SheetDescription>Choose a date, person, site or assignment status.</SheetDescription></SheetHeader>{form}</SheetContent></Sheet></div><span>{businessDate(filters.date)} · IST</span><button type="button" className="zb-att-icon-button" aria-label="Refresh team roster" disabled={loading} onClick={() => setVersion(v => v + 1)}><RefreshCw aria-hidden="true" /></button></div><div className="zb-deploy-desktop-filters">{form}</div>
    {(filters.query || filters.location || filters.status !== "ALL") && <div className="zb-deploy-filter-summary"><span>{[filters.query, filters.location, filters.status !== "ALL" ? deploymentLabels[filters.status].label : ""].filter(Boolean).join(" · ")}</span><button type="button" onClick={() => { const clear = { date: filters.date, query: "", location: "", status: "ALL" as const }; setFilters(clear); setDraft(clear); setPage(1); }}>Clear filters</button></div>}
    {loading ? <AttendanceLoading /> : error ? <DeploymentError admin={admin} error={error} retry={() => setVersion(v => v + 1)} /> : data && <>
      {data.requirement && <div className="zb-att-context"><UsersRound aria-hidden="true" /><span><strong>{data.requirement.companyName}</strong>{requirementServiceLabel(data.requirement.serviceRequired)} · {data.requirement.jobLocation}</span><Link className="zb-biz-text-link" href={deploymentHref(admin)}>All assignments</Link></div>}
      <div className="zb-deploy-metrics">{[{ value: data.counts.ACTIVE, label: "Active assignments", detail: `${data.workingOnDate} scheduled to work on this date`, icon: UsersRound }, { value: data.counts.UPCOMING, label: "Starting later", detail: "Confirmed future assignments", icon: CalendarClock }, { value: data.activeSites, label: "Active work locations", detail: "Sites covered by active assignments", icon: MapPin }, { value: data.endingSoon, label: "Ending within 7 days", detail: "Plan continuation or handover", icon: Flag }].map(({ value, label, detail, icon: Icon }) => <article key={label}><span><Icon aria-hidden="true" />{label}</span><strong>{value}</strong><small>{detail}</small></article>)}</div>
      {view === "schedule" && <div className="zb-deploy-week-heading"><div><h2>{businessDate(data.dates[0])} – {businessDate(data.dates[6])}</h2><p>Planned shifts for assignments overlapping this week. Cancelled assignments are excluded.</p></div><div><button className="zb-att-icon-button" type="button" disabled={moveDate(filters.date, -7) < "2000-01-01"} aria-label="Previous week" onClick={() => moveWeek(-7)}><ChevronLeft aria-hidden="true" /></button><button className="zb-att-icon-button" type="button" disabled={moveDate(filters.date, 7) > "2099-12-31"} aria-label="Next week" onClick={() => moveWeek(7)}><ChevronRight aria-hidden="true" /></button></div></div>}
      <div className="zb-att-result-line" role="status"><span>{data.total ? `${(data.page - 1) * data.pageSize + 1}–${Math.min(data.page * data.pageSize, data.total)} of ${data.total} assignments` : "No assignments in this view"}</span><small>{data.counts.ENDED} ended · {data.counts.CANCELLED} cancelled</small></div>
      {!data.total ? <div className="zb-att-empty"><UsersRound aria-hidden="true" /><h3>{filters.query || filters.location || filters.status !== "ALL" ? "No matching assignments" : "Your roster starts with a confirmed assignment"}</h3><p>{admin ? "Use New assignment to confirm a selected candidate’s location, dates and shift, or change these filters." : "Once our operations team confirms your selected candidates’ assignments, their sites and schedules will appear here. You can also try a different date or filter."}</p>{!admin && <Link className="zb-biz-text-link" href="/business/candidates">Review candidates<ArrowUpRight aria-hidden="true" /></Link>}</div> : view === "locations" ? <LocationGroups items={data.items} admin={admin} date={data.date} /> : view === "schedule" ? <div className="zb-deploy-schedule-list">{data.items.map(item => <article className="zb-deploy-schedule-card" key={item.id}><div><div><h3>{item.name}</h3><p>{item.role} · {item.location}{admin ? ` · ${item.requirement.companyName}` : ""}</p></div><Link className="zb-att-record-link" href={deploymentHref(admin, item.id, data.date)}>Assignment<ArrowUpRight aria-hidden="true" /></Link></div><WeekSchedule days={item.schedule} start={item.shiftStart} end={item.shiftEnd} /></article>)}</div> : <div className="zb-deploy-cards">{data.items.map(item => <RosterCard key={item.id} item={item} admin={admin} date={data.date} />)}</div>}
      <AttendancePages page={data.page} totalPages={data.totalPages} onChange={setPage} /><p className="zb-deploy-count-note">Summary counts follow the name, location and requirement filters{view === "schedule" ? " within this week" : ""}. The status filter applies to the listed assignments.</p>
    </>}
  </section>;
}
function RosterCard({ item, admin, date }: { item: RosterAssignment; admin: boolean; date: string }) {
  return <article className="zb-deploy-card"><div className="zb-deploy-card-person"><span className="zb-att-avatar" aria-hidden="true">{item.name.trim().split(/\s+/).slice(0, 2).map(word => word[0]).join("")}</span><div><h3>{item.name}</h3><p>{item.role}</p></div></div><DeploymentBadge state={item.state} />{admin && <p className="zb-deploy-company">{item.requirement.companyName}</p>}<dl><div><dt><MapPin aria-hidden="true" />Workplace</dt><dd>{item.location}</dd></div><div><dt><UserRoundCheck aria-hidden="true" />Supervisor</dt><dd>{item.supervisor}</dd></div><div><dt><CalendarDays aria-hidden="true" />Assignment dates</dt><dd>{businessDate(item.startDate)} – {businessDate(item.endDate)}</dd></div><div><dt><CalendarClock aria-hidden="true" />Shift · IST</dt><dd>{clock(item.shiftStart)}–{clock(item.shiftEnd)}{item.shiftEnd < item.shiftStart && <small>Ends the next day</small>}</dd></div></dl><WeekSchedule compact days={item.schedule} start={item.shiftStart} end={item.shiftEnd} /><Link className="zb-att-record-link" href={deploymentHref(admin, item.id, date)}>View assignment<ArrowUpRight aria-hidden="true" /></Link></article>;
}
function LocationGroups({ items, admin, date }: { items: RosterAssignment[]; admin: boolean; date: string }) {
  const groups = new Map<string, { name: string; items: RosterAssignment[] }>();
  for (const item of items) { const key = item.location.trim().toLocaleLowerCase(); const group = groups.get(key) ?? { name: item.location, items: [] }; group.items.push(item); groups.set(key, group); }
  return <div className="zb-deploy-location-groups"><p className="zb-deploy-count-note">Assignments are grouped by site on this page. A site can continue on the next page.</p>{[...groups].map(([key, group]) => <section key={key}><header><span><MapPin aria-hidden="true" /></span><div><h2>{group.name}</h2><p>{group.items.length} assignments on this page</p></div></header><div className="zb-deploy-cards">{group.items.map(item => <RosterCard key={item.id} item={item} admin={admin} date={date} />)}</div></section>)}</div>;
}
