"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, BriefcaseBusiness, CheckCircle2, MapPin, Search, Send, UsersRound } from "lucide-react";
import { ApiError } from "@/lib/api";
import { listPlacementCandidates, type PlacementCandidate } from "@/services/placement-candidates.service";
import { listPlacementOpportunities, submitCandidateForOpportunity, type PlacementOpportunity } from "@/services/placement-opportunities.service";

export function PlacementOpportunities(){const [items,setItems]=useState<PlacementOpportunity[]>([]);const [candidates,setCandidates]=useState<PlacementCandidate[]>([]);const [search,setSearch]=useState("");const [type,setType]=useState("");const [selectedJob,setSelectedJob]=useState<string|null>(null);const [candidateId,setCandidateId]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [success,setSuccess]=useState<string|null>(null);
useEffect(()=>{Promise.all([listPlacementOpportunities(),listPlacementCandidates()]).then(([o,c])=>{setItems(o.data.opportunities);setCandidates(c.data.candidates)}).catch(e=>setError(e instanceof ApiError?e.message:"Unable to load opportunities."))},[]);
const types=useMemo(()=>Array.from(new Set(items.map(x=>x.engagementType))).sort(),[items]);const visible=useMemo(()=>{const q=search.trim().toLowerCase();return items.filter(x=>(!type||x.engagementType===type)&&(!q||[x.title,x.category,x.engagementType,x.location,x.city,x.description].some(v=>v.toLowerCase().includes(q))))},[items,search,type]);
async function submit(jobId:string){if(!candidateId){setError("Select a candidate before submitting.");return}setBusy(true);setError(null);setSuccess(null);try{const r=await submitCandidateForOpportunity(jobId,candidateId,message||undefined);setSuccess(`${r.data.application.placementCandidate?.fullName??"Candidate"} submitted successfully.`);setSelectedJob(null);setCandidateId("");setMessage("")}catch(e){setError(e instanceof ApiError?e.message:"Unable to submit candidate.")}finally{setBusy(false)}}
return <div className="zb-placement-opportunity-shell"><header className="zb-candidate-toolbar"><div><Link href="/placement-portal"><ArrowLeft/>Portal dashboard</Link><p className="zb-eyebrow">Opportunity matching</p><h1>Jobs, internships & flexible opportunities</h1><p>Match institution candidates with currently open ZOBHUNGER opportunities.</p></div><Link className="zb-placement-secondary-link" href="/placement-portal/applications">Track applications</Link></header>{error&&<p className="zb-login-error">{error}</p>}{success&&<p className="zb-placement-success"><CheckCircle2/>{success}</p>}<section className="zb-opportunity-filterbar"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search title, location or category"/></label><select value={type} onChange={e=>setType(e.target.value)}><option value="">All opportunity types</option>{types.map(t=><option key={t}>{t}</option>)}</select><span>{visible.length} open</span></section><div className="zb-opportunity-grid">{visible.length===0?<div className="zb-candidate-empty"><BriefcaseBusiness/><strong>No matching opportunities</strong><span>Adjust the filters or check again when new roles are published.</span></div>:visible.map(job=><article className="zb-opportunity-card" key={job.id}><div className="zb-opportunity-card-top"><span>{job.engagementType}</span><small>{job.category}</small></div><h2>{job.title}</h2><p className="zb-opportunity-location"><MapPin/>{job.location}</p><p>{job.description}</p>{job.compensation&&<strong className="zb-opportunity-pay">{job.compensation}</strong>}<button onClick={()=>{setSelectedJob(selectedJob===job.id?null:job.id);setError(null);setSuccess(null)}}><UsersRound/>Match a candidate</button>{selectedJob===job.id&&<div className="zb-opportunity-submit-panel"><label>Candidate<select value={candidateId} onChange={e=>setCandidateId(e.target.value)}><option value="">Select candidate</option>{candidates.map(c=><option value={c.id} key={c.id}>{c.fullName} · {c.course}</option>)}</select></label><label>Note <span>Optional</span><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Add a short note for the opportunity team."/></label><button disabled={busy||!candidateId} onClick={()=>void submit(job.id)}><Send/>{busy?"Submitting...":"Submit candidate"}</button></div>}</article>)}</div></div>}
