"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { BriefcaseBusiness, FileCheck2, GraduationCap, LogOut, UsersRound } from "lucide-react";
import { ApiError } from "@/lib/api";
import { logout } from "@/services/auth.service";
import { getPlacementCellProfile, type PlacementCellProfile } from "@/services/placement-cell-access.service";

export function PlacementPortalDashboard(){const router=useRouter();const [profile,setProfile]=useState<PlacementCellProfile|null>(null);const [error,setError]=useState<string|null>(null);useEffect(()=>{getPlacementCellProfile().then(r=>setProfile(r.data.profile)).catch(e=>{setError(e instanceof ApiError?e.message:"Unable to load portal.");if(e instanceof ApiError&&(e.status===401||e.status===403)) router.replace("/placement-cell-login")})},[router]);async function signOut(){await logout();router.push("/placement-cell-login");router.refresh()}if(!profile&&!error)return <div className="zb-placement-portal-loading">Loading your institution partner workspace...</div>;if(error)return <div className="zb-login-error">{error}</div>;if(!profile)return null;return <div className="zb-placement-portal-shell"><header className="zb-placement-portal-header"><div><p className="zb-eyebrow">Institution Partner Portal</p><h1>{profile.institutionName}</h1><p>{profile.placementCellName} · {profile.city}, {profile.state}</p></div><button onClick={signOut}><LogOut/>Logout</button></header><div className="zb-placement-portal-stats"><Link className="zb-placement-portal-stat-link" href="/placement-portal/candidates"><UsersRound/><div><strong>Candidate records</strong><span>Add, update and manage student profiles</span></div></Link><Link className="zb-placement-portal-stat-link" href="/placement-portal/opportunities"><BriefcaseBusiness/><div><strong>Opportunities</strong><span>Match candidates with open jobs and internships</span></div></Link><Link className="zb-placement-portal-stat-link" href="/placement-portal/applications"><FileCheck2/><div><strong>Applications</strong><span>Track candidate submissions and statuses</span></div></Link></div><div className="zb-placement-portal-grid"><section><p className="zb-eyebrow">Institution profile</p><h2>Approved partner details</h2><dl><div><dt>Representative</dt><dd>{profile.contactPersonName}, {profile.designation}</dd></div><div><dt>Official email</dt><dd>{profile.officialEmail}</dd></div><div><dt>Institution type</dt><dd>{profile.institutionType}</dd></div><div><dt>Students</dt><dd>{profile.numberOfStudents.toLocaleString()}</dd></div><div><dt>Courses / departments</dt><dd>{profile.coursesDepartments}</dd></div></dl></section><aside><GraduationCap/><p className="zb-eyebrow">Portal foundation active</p><h2>Your institutional workspace is ready.</h2><p>Candidate management, opportunity matching and application tracking are active in your approved institutional workspace.</p><Link href="/placement-cell-partnership">View partnership program</Link></aside></div></div>}
